pom.xml
If you try to use a non-default codec in an OSGi situation, the bundle fails to start. In order to resolve this, the codec package needs to be exposed in the OSGi manifest.
=> Expose org.redisson.codec package for OSGi bundles

pom.xml
After further investigation, there seems to be a few packages that are not exported which are required. For example, the class RedisException. Rather than adding each package to the export-package list, use the maven-bundle-plugin to generate the exports using the in-built filters.
=> Remove Export-Package and allow maven-bundle-plugin to use defaults

src/main/java/com/lambdaworks/redis/RedisAsyncConnection.java, src/test/java/org/redisson/RedissonMapTest.java
RedisAsyncConnection.hmget encodes the fields parameter using addKeys rather than addMapKeys. When strings are used for keys, using the default JsonJacksonCodec, these keys are normally quoted when stored in redis, but addKeys does not quote these strings making the ReddisonMap.getAll, which uses hmget, return an empty map in all scenarios.
=> Incorrect map key encoding makes RMap.getAll return no fields

src/main/java/org/redisson/RedissonBlockingQueue.java, src/test/java/org/redisson/RedissonBlockingQueueTest.java
Found incorrect behaviour of queue.drainTo(collection, maxElements). It was filling the collection of elements with a trimming  all another elements in redis list. So, all subsequent calls of method returned collection of duplicated elements.
=> Bugfix for RedissonBlockingQueue#drainTo method with maxElements

src/main/java/com/lambdaworks/redis/protocol/Command.java, src/main/java/com/lambdaworks/redis/protocol/CommandOutput.java, src/main/java/com/lambdaworks/redis/protocol/RedisStateMachine.java, src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java, src/test/java/org/redisson/RedissonMapTest.java
This pull request is related to #169. First commit is just adding test case that is proving reported bug in the issue.
Second commit is proposed simple fix. Feel free to give me some feedback if anything needs to be changed or improved.
Have in mind, that this solution only protects CommandHandler from exceptions in CommandOutput.set methods. If exception is thrown somewhere else in RedisStateMachine, bug will still exists even after this fix.
=> Propagate response processing exceptions to ConnectionManager

src/main/java/org/redisson/connection/SentinelConnectionManager.java
Fixes what I mentioned in this comment: https://github.com/mrniko/redisson/issues/198#issuecomment-134493830
Checked through `client list` in redis-cli and it works
=> Add clientName to MasterSlaveServersConfig in SentinelConnectionManager

src/main/java/org/redisson/SingleServerConfig.java, src/main/java/org/redisson/connection/SingleConnectionManager.java
With AWS ElastiCache replication groups there is no autodiscovery of nodes or in-client notification of failovers. Instead Elasticache changes the primary endpoint DNS to point to the newly promoted master. This leads to issues like https://github.com/mrniko/redisson/issues/241
This change allows monitoring of the endpoint to see if the underlying host address has changed. If it has changed, `changeMaster()` is invoked to shutdown the old client and start a new one.
Example code for testing:
```java
public static void main(String[] args) {
// must ensure the JVM isn't caching DNS lookups
java.security.Security.setProperty("networkaddress.cache.ttl", "1");
Config config = new Config();
config.useSingleServer().setAddress(args[0]).setDnsMonitoring(true);
Redisson r = …
```
=> DNS monitoring for SingleServerConnection

src/main/java/org/redisson/RedissonMap.java
The `iterator` method in RedissonSet is public. It would be useful to make the RedissonMap iterator public, too, enabling iteration over hashes with millions of keys without memory issues.
=> Make the iterator method public

pom.xml, src/main/java/org/redisson/reactive/RedissonMapReactive.java
Generic type is added back in since the diamond operator "<>" is only available for source version 7 or above.
See:
https://docs.oracle.com/javase/tutorial/java/generics/types.html#diamond
=> fix "diamond operator is not supported in -source 1.6" error.

pom.xml
If you cache domain models (i.e. via the Serialization-Codec) within an
OSGi-environment and want to retrieve those back you will hit
ClassNotFoundException as the Redis-Bundle doesn't import the
appropriate packages. One way to avoid this would be the additional
"<DynamicImport-Package>*</DynamicImport-Package>" declaration for the
OSGi headers,
FIXES #410
=> Add DynamicImport-Package to OSGi headers

src/main/java/org/redisson/client/codec/StringCodec.java
The UTF-8 codec does not work well for arbitrary binary data. For
binary data, it might be good to use a codec like ISO_8859_1.
=> Add a constructor to StringCodec that allows for a supplied codec.

src/main/java/org/redisson/cluster/ClusterConnectionManager.java, src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java
When connection error occurs in `{MasterSlave,Cluster}ConnectionManager` constructor, `HashedWheelTimer` is not stopped, which leaves its thread running until application is killed.
=> Stop HashedWheelTimer after exception in constructor

src/test/java/org/redisson/RedisRunner.java, src/test/java/org/redisson/RedissonMultiLockTest.java, src/test/java/org/redisson/RedissonTest.java, src/test/resources/redis_connectionListener_test.conf, src/test/resources/redis_multiLock_test_instance1.conf, src/test/resources/redis_multiLock_test_instance2.conf, src/test/resources/redis_multiLock_test_instance3.conf, src/test/resources/redis_oom_test.conf
Currently tests are bound to a certain setup on Windows.
This PR enables running them on Linux and Mac OS X with discovering redis-server executable in PATH, saving behavior for your environment.
=> Untie tests from Windows absolute paths

src/main/java/org/redisson/RedissonSet.java
In removeAll method, wrong list was passed to the command executor.
=> Fixed removeAll bug in RedissonSet

src/test/java/org/redisson/RedissonGeoTest.java
Since 3.2.0, the GEODIST command seems always rounding up the result to 4 digits decimal places.
=> Looks like the Redis spec has changed

src/main/java/org/redisson/RedissonRemoteService.java, src/test/java/org/redisson/RedissonRemoteServiceTest.java
We probably don't want to issue a remote call when calling `toString`, `equals` and `hashCode` on the `RedissonRemoteService` client proxy.
This one is debatable. Just discard the PR if you don't agree :)
=> no remote call for toString, equals and hashCode on the client proxy

src/main/java/org/redisson/remote/RRemoteServiceResponse.java, src/main/java/org/redisson/remote/RemoteServiceAck.java, src/main/java/org/redisson/remote/RemoteServiceRequest.java, src/main/java/org/redisson/remote/RemoteServiceResponse.java, src/test/java/org/redisson/RedissonRemoteServiceTest.java
This contains two tests to show that Remote Service does not work with a serialization based codec.
I know this could be a design choice to not support serialization in Remote Service.
Indeed, it cause less upgrade problem if users use the default JSON based codec that is not subject to `InvalidClassException` caused by incompatible serialized form and wrong `serialVersionUID` and such.
Though, this one has an easy fix I can push to this PR if you feel this is a bug and not a design choice.
=> Tests for Redisson Remote Service with serialization based codec

src/main/java/org/redisson/RedissonRemoteService.java, src/main/java/org/redisson/core/RRemoteService.java, src/main/java/org/redisson/core/RemoteInvocationOptions.java, src/main/java/org/redisson/remote/RemoteServiceRequest.java, src/test/java/org/redisson/RedissonRemoteServiceTest.java
This PR feels like a hack, because I made this just as a proof of concept.
I am very open to discuss this further.
Whit this PR, one can make unacknowledged and/or fire-and-forget calls (see #494).
In the `RRemoteService`'s `get(...)` methods that accepts `executionTimeout` and/or `ackTimeout`:
- pass a negative value into `executionTimeout` to make fire-and-forget calls
- pass a negative value into `ackTimeout` to make unacknowledged calls
There is many things not quite right with this implementation, here some that comes to mind:
- from a user perspective, it is not clear that a fire-and-forget call will returns the default value for the method return type (`0` for `int`, `null` for `Object`, etc...), so it is a bit misleading (the user explicitly want the call to return without result, …
=> proof of concept for unacknowledged and/or fire-and-forget calls in RRemoteService

src/main/java/org/redisson/client/codec/JsonJacksonMapValueCodec.java, src/main/java/org/redisson/codec/JsonJacksonCodec.java, src/test/java/org/redisson/RedissonCodecTest.java, src/test/java/org/redisson/client/codec/JsonJacksonMapValueCodecTest.java
Closed #532. See RedissonCodecTest for usage examples. I've had to change JsonJacksonCodec to use decoder, encoder members explicitly otherwise overriding just the map value ones would override all of them.
Also rearranged the methods in RedissonCodecTest, so they make more sense - test() method last.
=> A basic typed map value codec.

src/main/java/org/redisson/RedissonSet.java, src/main/java/org/redisson/RedissonSetMultimapValues.java, src/main/java/org/redisson/api/RSetReactive.java, src/main/java/org/redisson/client/protocol/RedisCommands.java, src/main/java/org/redisson/core/RSet.java, src/main/java/org/redisson/core/RSetAsync.java, src/main/java/org/redisson/reactive/RedissonSetReactive.java, src/test/java/org/redisson/RedissonSetReactiveTest.java, src/test/java/org/redisson/RedissonSetTest.java
This adds `RSet.random()` and `RSetAsync.randomAsync()` support via the `SRANDMEMBER` command.  Getting a random member without removing it from the set.
=> Add support for getting a random set member

redisson/src/main/java/org/redisson/config/Config.java, redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java
If the executor/eventloop are shared among multiple Redisson instances shutting down of this Redissons shouldn't close the shared executor/eventloop
=> Don't close shared instances of ExecutorService or EventLoopGroup

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java, redisson/src/test/java/org/redisson/RedissonLocalCachedMapSerializationCodecTest.java, redisson/src/test/java/org/redisson/RedissonLocalCachedMapTest.java
Add a version of RedissonLocalCachedMapTest that uses the SerializationCodec.
Fix most of the tests by making classes implement Serializable.
The testAddAndGet test is still failing and after an hour of looking through it, I still can't figure why. It has something to do with encoding the key, which is an Integer object, and then redis gives the error: ERR hash value is not a valid float
So this pull request gets most of the way there, but I'm still missing the last part of making RedissonLocalCachedMap (tests) work with SerializationCodec.
=> RedissonLocalCachedMap doesn't work with SerializationCodec or FstCodec

.travis.yml, redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java, redisson/src/main/java/org/redisson/api/LocalCachedMapOptions.java, redisson/src/main/java/org/redisson/misc/AbstractCacheMap.java, redisson/src/main/java/org/redisson/misc/CachedValue.java, redisson/src/main/java/org/redisson/misc/LFUCacheMap.java, redisson/src/main/java/org/redisson/misc/SoftCacheMap.java, redisson/src/main/java/org/redisson/misc/SoftCachedValue.java, redisson/src/main/java/org/redisson/misc/StdCachedValue.java, redisson/src/test/java/org/redisson/misc/SoftCacheMapTest.java
With soft references the JVM will evict items from the local values when it's running out of memory.
=> Add an option to use soft references for eviction with LocalCachedMap.

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
Support for the `handshake` flag/status of a cluster node was apparently never fully implemented.  I think it's as simple as this.
=> Skip cluster nodes with the "handshake" flag

redisson/src/main/java/org/redisson/spring/support/RedissonDefinitionParser.java, redisson/src/main/java/org/redisson/spring/support/RedissonMultiLockDefinitionParser.java, redisson/src/main/resources/org/redisson/spring/support/redisson-1.0.xsd, redisson/src/test/java/org/redisson/RedisRunner.java, redisson/src/test/java/org/redisson/spring/support/SpringNamespaceWikiTest.java, redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_cluster.xml, redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_master_slave.xml, redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_replicated.xml, redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_sentinel.xml, redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_single.xml
Removed the workaround for multi-lock namespace definition
Employed proper solution where dependencies are explicitly defined to help spring create beans in a desired order.
Merged with master
Modified redisson.xsd to be inline with recent config changes
Fixed some typo
A better way to resolve master address URL
Added test cases to cover the examples mentioned in the wiki page.
=> Additional namespace refinement

redisson/src/test/java/org/redisson/RedissonCodecTest.java
On this pull request we add test coverage for org.redisson.codec.AvroJacksonCodec by fixing an wrong variable assignment at org.redisson.RedissonCodecTest
There is already an open issue raising this point: #799
=> Add test coverage for org.redisson.codec.AvroJacksonCodec

redisson/pom.xml, redisson/src/main/java/org/redisson/spring/cache/RedissonCache.java, redisson/src/main/java/org/redisson/spring/cache/RedissonCacheStatisticsAutoConfiguration.java, redisson/src/main/java/org/redisson/spring/cache/RedissonCacheStatisticsProvider.java, redisson/src/main/resources/META-INF/spring.factories
Support Spring Boot Actuator cache metrics: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-datasource-cache
With this change, Spring Boot will automatically (via RedissonCacheStatisticsAutoConfiguration) pick up the Redisson cache statistics provider. If the user doesn't use Spring Boot, nothing changes - Spring Boot is not a required dependency (just like how Spring itself isn't a Redisson required dependency).
=> Add an autoconfigured Spring Boot CacheStatisticsProvider implementation

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
So 
- One can implement his/her own local cache storage (e.g. offheap based)
- Or wrap actual local cache with a proxy to intercept calls for some reasons (e.g. metric)
- ...
=> Make local cache creation overridable in `RedissonLocalCachedMap`

redisson/src/main/java/org/redisson/spring/cache/RedissonCacheStatisticsAutoConfiguration.java
Actuator is an optional feature in Spring Boot, there are a lot of projects that do not use actuator due to additional dependencies and complexity. 
Redisson 3.3.1 worked fine without actuator but 3.3.2 fails to start with ClassNotFoundException for  org.springframework.boot.actuate.cache.CacheStatisticsProvider.
Suggested change registers Redisson AutoConfiguration only if actuator is in the classpath
=> Spring boot with redisson 3.3.2 fails without optional actuator dependency

redisson/src/main/java/org/redisson/RedissonGeo.java, redisson/src/main/java/org/redisson/api/RGeo.java, redisson/src/main/java/org/redisson/api/RGeoAsync.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonGeoTest.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
See issue #855
This code mostly works, but there is a strange issue with empty results. When the result is empty (no members within this radius), the query times out instead of returning 0. I might have misused the Command or Codec?
Hopefully someone more familiar with Redisson internals can help.
Failed Tests:
```
1. RedissonGeoTest.testRadiusStoreMemberEmpty
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (GEORADIUSBYMEMBER) with params: [test, Palermo, 200.0, km, STORE, test-store]
at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:646)
...
2. RedissonGeoTest.testRadiusStoreEmpty
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (GEORADIUS) with params: …
```
=> Support STORE parameter for GEORADIUS and GEORADIUSBYMEMBER

redisson/pom.xml
closes https://github.com/redisson/redisson/issues/901
cc/ @mrniko
=> Update Jackson dependencies to version 2.7.6

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/MapOptions.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
Currently RedissonMapCache creates an unbounded set in Redis which may cause problems in certain cache implementations.
Thanks for the heavy lifting @zuanoc !
=> Add support for bounded Redisson map cache (max size configuration). 

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/MapOptions.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
Currently RedissonMapCache creates an unbounded set in Redis which may cause problems in certain cache implementations.
=> Add support for bounded Redisson map cache (max size configuration).

redisson/src/main/java/org/redisson/RedissonLiveObjectService.java, redisson/src/main/java/org/redisson/RedissonReference.java, redisson/src/main/java/org/redisson/codec/DefaultCodecProvider.java, redisson/src/main/java/org/redisson/liveobject/core/AccessorInterceptor.java, redisson/src/main/java/org/redisson/liveobject/core/LiveObjectInterceptor.java, redisson/src/main/java/org/redisson/liveobject/core/RedissonObjectBuilder.java, redisson/src/main/java/org/redisson/liveobject/misc/ClassUtils.java, redisson/src/main/java/org/redisson/liveobject/misc/Introspectior.java, redisson/src/main/java/org/redisson/misc/RedissonObjectFactory.java, redisson/src/test/java/org/redisson/RedissonLiveObjectServiceTest.java
Addresses issue #930 
I hope I caught all the relevant usages of `@REntity` and `@RId`. See the additional test `RedissonLiveObjectServiceTest.testInheritedREntity()` to see an example.
=> Allow LiveObjectService to work with classes that inherit from REntities

redisson/src/main/java/org/redisson/liveobject/core/AccessorInterceptor.java, redisson/src/test/java/org/redisson/RedissonLiveObjectServiceTest.java
Objects cannot be detached from RedissonLiveObjectService if they have accessors in the `isBooleanValue()` style - this will cause an exception. This PR addresses that issue.
=> Bugfix: accessor methods in Live Objects break if they start with 'is'

redisson/src/main/java/org/redisson/connection/pool/ConnectionPool.java
Following my issue: https://github.com/redisson/redisson/issues/1077
I think that the acquireConnection() should be call when a connexion is freezed with the reason entry.getFreezeReason() == FreezeReason.SYSTEM for MASTER and SLAVE too.
With this modification I have the good behavior in test mode: 1 master and 1 slave, 1 sentinel.
If I kill the slave, and then restart it, the slave come back in the pool and can be used for read-only operations.
=> Try and AcquireConnection when entry is FreezeReason SYSTEM not only for MASTER

redisson-tomcat/redisson-tomcat-6/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
This is to support child classes that can override the configuration behavior to do something different than just read a file. In our case we need to be able to programmatically configure the client so we can't rely on a static file somewhere.
I only changed the tomcat 8 session manager, but I would gladly change the older tomcat 6 & 7 managers to make them consistent if you want.
I could also submit a new manager extending this with the properties directly on the manager similar to https://github.com/chexagon/redis-session-manager.
=> Separate client construction into separate method

redisson/src/main/java/org/redisson/connection/pool/ConnectionPool.java
Submitting this fix, following the feedback from @mrniko on [this changeset](https://github.com/redisson/redisson/commit/f784778c97672fdc12684395db9958ff77263d4c
) confirming that this is a desirable change.
Here i'm just replicating the same condition present in the [other get method](https://github.com/joseduraes/redisson/blob/f25f12f84441174aeda5e2545c2846a4ba6eb068/redisson/src/main/java/org/redisson/connection/pool/ConnectionPool.java#L200) from this class (which has a different signature), to tentatively unfreeze a node, which was missing here.
I wondered if this logic could/should be centralized for better maintainability, but i'm not yet too comfortable with the codebase, so kept this straightforward.
Many thanks for this great project.
=> Add missing condition for tentatively unfreezing node

redisson/src/main/java/org/redisson/RedissonObject.java
They do not use any instance variables or instance context, and making them static allows for easier extension of Redisson with custom functionality on Redisson internal admin/management objects.
=> Make prefixName and suffixName be static methods

redisson-tomcat/redisson-tomcat-6/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
Currently there is no way to customise tomcat session key for redis, which is always "redisson_tomcat_session:" + sessionId.
But in environment where multiple tomcat instances are using same redis cluster in it not possible to distinguish different tomcat instances.
In this pull request I have added configuration option for tomcat session key prefix, while configuring session manager use following configuration to customise tomcat session key prefix.
`<Manager className="org.redisson.tomcat.RedissonSessionManager" 
configPath="${catalina.base}/redisson.conf" 
readMode="MEMORY" updateMode="DEFAULT" keyPrefix="this_is_a_test_prefix"/>`
this will allow redisson to store tomcat session keys using following keys
`this_is_a_test_prefix:redisson_tomcat_session:E61653A9FEE61CB5D0967C2C40451363`
=> Configurable Tomcat Session Key Prefix for Redis

redisson-tomcat/redisson-tomcat-6/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
Fixed missing colon in user defined tomcat key prefix in redis.
Problematic key format
this_is_a_test_prefixredisson_tomcat_session:E61653A9FEE61CB5D0967C2C40451363
expected key format
this_is_a_test_prefix:redisson_tomcat_session:E61653A9FEE61CB5D0967C2C40451363
Reference: https://github.com/redisson/redisson/pull/1321
=> Fixed missing colon in user defined tomcat redis key prefix.

redisson/src/main/java/org/redisson/misc/CompositeIterable.java, redisson/src/main/java/org/redisson/misc/CompositeIterator.java, redisson/src/test/java/org/redisson/misc/CompositeIteratorTest.java
An enhancement from [#1598](https://github.com/redisson/redisson/issues/1598), I think it would be less confused to separate Iterable and Iterator.  Any hints?
=> An enhancement from #1598 CompositeIterator decouple from CompositeIterable

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
Now SentinelConnectionManager splits host and port by first colon. That doesn't work for IPV6 adresses
=> Fix host-port splitter in SentinelConnectionManager for ipv6 addresses

redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
I was testing out different codecs in different environments connected to the same redis instance.  I provided a different `keyPrefix` in `context.xml` to prevent one environment's codec from messing with another environment's session management.  However, since the `keyPrefix` is only applied to the session contents themselves and not the topic subscription, codec errors were still present and causing a lot of log spew.
I expected `keyPrefix` to apply not only to the session contents but also to the topic updates, so I'm publishing this PR to see if you guys agree.
Here are example of updates for two different codecs with two different `keyPrefix` BEFORE this commit is applied.
+1544721052.037348 [0 10.0.1.184:40588] "publish" "redisson:tomcat_session_updates:" …
=> [tomcat] Apply `keyPrefix` to both session and topic keys

redisson/src/main/java/org/redisson/misc/URIBuilder.java
`URI.getHost()` method produces ip address with square brackets, but `InetSocketAddress.getAddress().getHostAddress()` does not. Therefore `compare` method never works for IPv6 address-formatted hosts.
=> Fix URIBuilder compare method for IPv6 hosts

redisson/src/main/java/org/redisson/RedissonLock.java, redisson/src/main/java/org/redisson/api/RLock.java
Using executors or thread pools for acquiring and releasing locks, it is not trivially possible to ensure the thread acquiring the lock is the same thread releasing a lock.
We use locks with expiration and would like to ensure we still hold the lock before unlocking. This will help guarentee we had the lock all through the lock-to-unlock.
Since call to unlock returns `true` if the lock does not exist, there is no other way to find out if we still own the lock, we need this ability to pass the thread ID and check if the lock is still held by the thread.
=> Check if lock held by thread

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
There is an issue in SentinelConnectionManager.slaveDown() method, that tries to convert to IPv6 format host that already was converted earlier.
=> Do not wrap in square brackets already wrapped IPv6 addresses

redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/UpdateValve.java
Adapted the Tomcat 7,8 and 9 UpdateValve to indicate that AsyncServlets are allowed.
See #1932 for the problem that it is trying to solve.
I don't have a specific unit test for testing out that this indeed works with an Async servlet in all these tomcat versions ... it is just to show to potentially fix the problem.
tomcat Javadoc does not really state what the implications is for this flag - I wonder why it is not on by default?
=> Allow tomcat RedissonSessionManager to support async servlets

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
Without shuffling, all clients end up always preferring the first sentinel on the list which can cause significant CPU load on that one sentinel.  This PR shuffles the list and distributes the load across all sentinels.
=> Shuffle the sentinel list so all clients don't prefer the same sentinel

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
According to the [documentation](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-findbyindexnamesessionrepository) setting a session attribute with the name of `FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME` should be enough to be able to find this session later with `RedissonSessionRepository.findByIndexNameAndIndexValue` but actually every time one needs to put the prefix `session-attr:` which violates the original contract
=> fixed RedissonSessionRepository according to Spring documentation

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java, redisson/src/main/java/org/redisson/spring/session/config/RedissonHttpSessionConfiguration.java
When i integration spring session, in `RedissonSessionRepository.class`, the created event can't be trigger,
if set `keyPrefix `on `RedissonHttpSessionConfiguration.class`. Cause event listener add on construct, at the same time, add create event listener apply keyPrefix. However, `RedissonSessionRepository.class keyPrefix` set on `RedissonHttpSessionConfiguration.class.`
`createdTopic = redisson.getPatternTopic(getEventsChannelPrefix() + "*", StringCodec.INSTANCE);`
```
RedissonSessionRepository repository = new RedissonSessionRepository(redissonClient, eventPublisher, keyPrefix);
if (StringUtils.hasText(keyPrefix)) {	
repository.setKeyPrefix(keyPrefix);	
}
```
=> Fixed - RedissonSessionRepository.class can't trigger created event,if set RedissonHttpSessionConfiguration.class keyPrefix attribute.

redisson-tomcat/redisson-tomcat-6/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-6/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/UpdateValve.java
Expected behavior
UpdateValve valve should be installed only once for tomcat pipeline but if there are multiple web application each one will instantiate a new RedissonSessionManager and each startInternal() will install it's own copy of the UpdateValve, more over the UpdateValve have back reference to RedissonSessionManager, so remove this reference in order to have only one UpdateValve installed for the tomcat pipeline and allow proper RedissonSessionManager garbage collection.
When we have Redisson client set in JNDI which is shared between web applications we need to remove MessageListener from the topic when web application is deinstalled during stopInternal method of RedissonSessionManager
Actual behavior
Each web app will create it's own RedissonSessionManager instance which will …
=> UpdateValve should be installed only once, remove MessageListener from topic when SessionManager stopInternal is invoked #2178

redisson/src/main/java/org/redisson/config/ConfigSupport.java, redisson/src/test/java/org/redisson/config/ConfigSupportTest.java
If a config contains multiple variables (in one line) with defaults like this:
```yaml
singleServerConfig:
address: 'redis://${REDIS_HOST:-127.0.0.1}:${REDIS_PORT:-6379}'
```
The parser failed because the regular expression threated them as one variable `REDIS_HOST:-127.0.0.1}:${REDIS_PORT` with default `6379`.
=> Support multiple environment variables with default

redisson/src/main/java/org/redisson/RedissonFairLock.java, redisson/src/test/java/org/redisson/RedissonFairLockTest.java
This is a fix for #2099 and a continuation of the fix for #1104.
This change alters how timeouts are calculated for threads added into the queue when the lock cannot be immediately acquired, and adds logic to reduce the timeouts when a thread leaves the queue by either acquiring the lock or timing-out while waiting.
The timeout drift issue is resolved by decreasing the timeouts in the redisson_lock_timeout sorted set when a thread is removed from the queue. This logic was added to the tryLockInnerAsync lua code (both variations):
```lua
if (redis.call('exists', KEYS[1]) == 0) and ((redis.call('exists', KEYS[2]) == 0)
or (redis.call('lindex', KEYS[2], 0) == ARGV[2])) then
redis.call('lpop', KEYS[2]);
redis.call('zrem', KEYS[3], ARGV[2]);
redis.call('hset', KEYS[1], ARGV[2], 1); …
```
=> Fix #2099 timeout drift in RedissonFairLock

redisson/src/main/java/org/redisson/api/RSetReactive.java, redisson/src/main/java/org/redisson/api/RSetRx.java, redisson/src/test/java/org/redisson/RedissonSetReactiveTest.java, redisson/src/test/java/org/redisson/rx/RedissonSetRxTest.java
Fixed #2241. Set.intersection, union and diff should return a Single, or Mono, of Integer, not Long.
=> Reactive intersection, union and diff should return Integer, not Long

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
There was already a fix https://github.com/redisson/redisson/commit/b7df3a2d293b7cce438d1bb795289cbb4da30f37
But it was lost in https://github.com/redisson/redisson/commit/a9f7a99388c3dabdc45157af61558975e0e61fdb#diff-7d2da5068938564117bd318316bdd1ad
=> Do not wrap in square brackets already wrapped IPv6 addresses v2

redisson/src/main/java/org/redisson/spring/cache/RedissonCacheStatisticsAutoConfiguration.java
The conditional is related to micrometer with `MeterProvider`, whereas the actual `RedissonCacheMeterBinderProvider` requires the actuator `CacheMeterBinderProvider`.
=> Spring boot fails without optional actuator dependency 3.11.5

redisson/src/main/java/org/redisson/RedissonBuckets.java, redisson/src/test/java/org/redisson/RedissonBucketsTest.java
I have run the unit tests related to this change and they pass.
=> Prevent NPE when a value from Redis is null

redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java
This PR fixes a bug that I ran into when replacing a lost replica with a replacement node that had the same DNS host name as the lost one. The scenario is as follows.
There are two nodes in replicated mode:
```
node-1.redis.my.domain[127.0.0.1] (primary)
node-2.redis.my.domain[127.0.0.2] (replica)
```
The replica is lost permanently and replaced with a node having a new ip address but same host name:
```
node-1.redis.my.domain[127.0.0.1] (primary)
node-2.redis.my.domain[127.0.0.3] (replica)
```
In such a scenario, the following observation can be made:
The discovery of a new mapping from DNS host name to ip address in `DNSMonitor` leads to the addition of a new replica entry in `MasterSlaveEntry` and consequently also in `LoadBalancerManger`. 
Now that there exist two entries with the …
=> reactivate replicas based on ip adress instead of hostname in ReplicatedConnectionManager

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
Moved the extraction of scheme from sentinel address in order to always be available regardless whether a password is required.
=> Fix for issue #2528 Now always extracting scheme from url for sentinel connections

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
Using Redis Enterprise requires to connect as if it was a standalone
redis although it is a redis cluster. While this is great from a
technical point of view this leads to a nasty error when using spring
session because renaming keys in a redis cluster is only possible if
the hashslots of the old and new key are the same.
The resulting error is
```
org.springframework.dao.InvalidDataAccessApiUsageException:
CROSSSLOT Keys in request don't hash to the same slot
(command='RENAME', original slot=12273, wrong slot=10406,
first key='spring:session:sessions:90ef42c7-xxxx-xxxx-800f-2d1a48d0aa07',
violating key='spring:session:sessions:477ba6b1-5b8e-xxxx-xxxx-d6adeab0b580');
```
By not using the RENAME command any more changeSessionId works on all
Redis distributions.
=> Change session id without renaming key

redisson-spring-boot-starter/src/main/java/org/redisson/spring/starter/RedissonAutoConfiguration.java, redisson-spring-boot-starter/src/main/java/org/redisson/spring/starter/RedissonAutoConfigurationCustomizer.java
Add a customizer interface that can be implemented by beans wishing to customize the RedissonClient auto configuration
=> Add an auto configuration customizer

redisson/src/main/java/org/redisson/RedissonKeys.java
Signed-off-by: Aayushya Vajpayee <aayushyavajpayee@gmail.com>
=> unlink method calls deleteAsync inside instead of unlinkAsync

pom.xml
The used doclint option is not valid anymore. Use the correct <doclint> configuration option.
=> Migrate javadoc plugin configuration to used version

.github/workflows/maven.yml
The build has a lot of output and on the other hand we do not need to download the packages each time so this pr adds a caching step. Also upgrades the checkout action to v2
=> Add github actions cache step and upgrade checkout to v2

redisson/pom.xml
The configuration key has an typo.
=> Use correct linkXRef instead of linkXref for pmd plugin

pom.xml, redisson-all/pom.xml
Enforcer plugin should be used in maven project and <prerequisites> in maven-plugin projects.
=> Use enforcer plugin instead of prerequisites

redisson/src/main/java/org/redisson/RedissonRateLimiter.java, redisson/src/main/java/org/redisson/api/RRateLimiter.java, redisson/src/main/java/org/redisson/api/RRateLimiterAsync.java, redisson/src/main/java/org/redisson/api/RRateLimiterReactive.java, redisson/src/main/java/org/redisson/api/RRateLimiterRx.java, redisson/src/test/java/org/redisson/RedissonRateLimiterTest.java
Addresses https://github.com/redisson/redisson/issues/2322. Added methods to update(overwrite) a rate. The methods 'hset'(as opposed to 'hsetnx') is used to update the rate config, and also delete the {name}:permits and {name}:value entries, which are then created during the next instance of acquire.
=> Rate limiter update rate

redisson/src/main/java/org/redisson/config/ConfigSupport.java, redisson/src/test/java/org/redisson/config/ConfigSupportTest.java
Expand config variables from system properties if not found as environment variables. From the javadoc on System.getenv " It is best to use system properties where possible." (https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#getenv-java.lang.String-)
Allow '.' in config variable names: REDIS.HOST as well as REDIS_HOST. It's common to use '.' in the middle of system property names.
This is motivated by a move from using redis-session-manager (https://github.com/chexagon/redis-session-manager) to using RedissonSessionManager. We have extensive configuration using system properties across environments to configure our Redisson clients programmitically and it's much easier to modify ConfigSupport to support the same properties in yaml than it is to modify the environment …
=> Expand config variables from system properties if not found as environment variables.

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
We faced into the issue where the CLUSTER NODES command is only sent to the same node.
=> Preventing sending CLUSTER NODES to the same host

redisson-spring-boot-starter/src/test/resources/redisson.yaml
If you look at "Files changed" it looks like not much has changed. But actually, as described in #3208, the encoding of the files is changed.
The encoding is changed with Notepad++.
**Old version**
**New version**
**Additional Sources**
According to the [Unicode standard](http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf):
> Use of a BOM is neither required nor recommended for UTF-8, but may
be encountered in contexts where UTF-8 data is converted from other encoding forms that
use a BOM or where the BOM is used as a UTF-8 signature. 
[What's the difference between UTF-8 and UTF-8 without BOM?](https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom#:~:text=The%20UTF%2D8%20BOM%20is,8%2C%20the%20BOM%20is%20unnecessary.)
=> Fix - Change the encoding of redisson.yaml from UTF-8-BOM to UTF-8.

redisson-spring-boot-starter/README.md
```java
@ConfigurationProperties(prefix = "spring.redis.redisson")
public class RedissonProperties {
... 
}
```
due to `RedissonProperties` prefix is `spring.redis.redisson`, so the `redis` level is parent of `redisson`
but in README they are in same level.
=> feat: fix doc

redisson-spring-data/redisson-spring-data-16/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-17/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-18/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-20/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-21/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java, redisson-spring-data/redisson-spring-data-23/src/test/java/org/redisson/spring/data/connection/PropertiesDecoderTest.java
I'm using Redisson with Spring Boot 2.3.5. When Spring Boot's health actuator of health is enabled and health endpoint is visited, health status of redis will be accessed through `org.redisson.spring.data.connection.RedissonReactiveServerCommands#info()`, then `PropertiesDecoder#decode` is used to decode responded string from `INFO` command.
However if no sections are provided to `INFO` command, size of responding string can be up to 3.5KB. If a low health check interval, like 2 seconds, is set, decoding the result costs significant CPU time:
To enhance the performance for decode method, splitting result with single char can be used instead of regular expression. 
Benchmark from `org.redisson.spring.data.connection.PropertiesDecoderTest#benchmark`:
Old: 2410ms
New: 960ms
=> Enhance PropertiesDecoder decoding performance

redisson/src/main/java/org/redisson/RedissonMap.java
This is shown in the following code
```java
public RFuture<V> putIfAbsentAsync(K key, V value) {
checkKey(key);
checkValue(key);
RFuture<V> future = putIfAbsentOperationAsync(key, value);
if (hasNoWriter()) {
return future;
}
MapWriterTask.Add task = new MapWriterTask.Add(key, value);
return mapWriterFuture(future, task, r -> r == null);
}
```
```java
public RFuture<V> putIfAbsentAsync(K key, V value) {
checkKey(key);
checkValue(value);
RFuture<V> future = putIfAbsentOperationAsync(key, value);
if (hasNoWriter()) {
return future;
}
MapWriterTask.Add task = new MapWriterTask.Add(key, value);
return mapWriterFuture(future, task, Objects::isNull);
}
```
=> Fix check parameter code error and optimize code format

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java, redisson/src/main/java/org/redisson/api/LocalCachedMapOptions.java, redisson/src/test/java/org/redisson/RedissonLocalCachedMapTest.java
This is the first PR that I open to an open source project :)
These are the changes that I made to implement feature #3221:
- Added `allowNullValues` to `LocalCachedMapOptions` with a `false` default value.
- Modified the `RedissonLocalCachedMap.init()` method to initialize the `allowNullValues` attribute.
- Modified the `RedissonLocalCachedMap.getAsync(Object key)` method to be able to store a null value into the local cache when the value is not found in Redis and `allowNullValues` is true.
- Override the `RedissonLocalCachedMap.checkValue(Object value)` method to avoid throwing a `NullPointerException` when the value is null and `allowNullValues` is true.
- Added some tests to `RedissonLocalCachedMapTest` to check the feature. I found that this class is excluded from …
=> Feature - Added option to allow null values in a local cache #3221

redisson/src/main/java/org/redisson/config/SentinelServersConfig.java, redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
* Added new configuration field to allow a different password to be
used for authenticating against sentinel nodes
In order to address https://github.com/redisson/redisson/issues/3030
where sentinel is configured with a password that is not the same as the credentials used to connect to redis.
Example: We created an ACL user entry for our application to have a reduced set of permissions (only allow access to keys matching a prefix and no dangerous commands). but we still want to use sentinel, the app needs to connect to redis as the acl user, and use the sentinel's password when talking there.
=> Configure Sentinel Password

redisson/src/main/java/org/redisson/jcache/JCacheManager.java
I have a case when the underlying cache provider is being selected and configured programmatically. In particular, I need to configure a Redisson client beforehand and create an instance of JCacheManager directly without using JCachingProvider.
=> Make JCacheManager constructor public

redisson/src/main/java/org/redisson/client/RedisClient.java
#3404, The netty enentLoop was blocked by try to resolve the hostname of the org.redisson.client.RedisClient#resolveAddr's InetSocketAddress.
=> try fix the issue #3404, SENTINEL SENTINELS timeout

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
I'm using Redisson to interact with my Elasticache Redis cluster. The configuration is 15 shards with only primary nodes.
If I create a replica for one shard and failover the primary node to the replica, the new connection won't be established.
=> Fix primary update condition for cluster mode.

redisson/src/main/java/org/redisson/remote/BaseRemoteProxy.java, redisson/src/main/java/org/redisson/remote/BaseRemoteService.java
This pull request simplifies the implementation of `getRequestQueueName` using `Map::computeIfAbsent`.
This patch was generated automatically using the static analysis tool [Logifix](https://github.com/lyxell/logifix) as part of a research project.
=> Simplify code using Map::computeIfAbsent

redisson/src/main/java/org/redisson/RedissonList.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonListTest.java
There appears to be a bug in how the response from `RList.remove(object, count)` is parsed when more than 1 object is removed. Previously `BooleanReplayConvertor` was used where it appears that `BooleanAmountReplayConvertor` should be used since the LREM response can be greater than 1 (if multiple items are removed).
Here's a fix & accompanying unit test - please let me know if I should make any changes or if you have any suggestions.
Example code that shows the problem:
```
redissonClient.getList("one_item").clear();
redissonClient.getList("two_items").clear();
redissonClient.getList("one_item").add("item");
redissonClient.getList("two_items").addAll(Arrays.asList("item", "item"));
assertEquals(1, redissonClient.getList("one_item").size());
assertEquals(2, …
```
=> Fix RList remove with count response when multiple items are removed

redisson-spring-data/redisson-spring-data-16/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-17/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-18/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-20/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-21/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-24/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-25/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-26/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java
I found some codec problem when I am doing some work with RedissonConnection#eval .
Using Spring's RedisTemplate execute script like this will fail into assert eror.
Should RedisConnection#eval use ByteArrayCodec.INSTANCE just like RedisConnection#evalSha ?
So I create this PR.
Thanks for your time.
```java
RedisTemplate<String, Object> redisTemplate = t();
String script = "return ARGV[1];";
DefaultRedisScript<byte[]> redisScript = new DefaultRedisScript<>(script, byte[].class);
byte[] results = redisTemplate.execute(redisScript, Collections.singletonList("any"), new byte[]{5, 11, 2, 3});
assertEquals(results[0], 5);
assertEquals(results[1], 11);
assertEquals(results[2], 2);
assertEquals(results[3], 3);
```
More information : `org.springframework.data.redis.core.script.DefaultScriptExecuto …
=> Fixed: RedissonConnection eval should use ByteArrayCodec

redisson-spring-data/redisson-spring-data-24/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-25/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-26/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java
Hello. I found `RedissonConnection` does not override default implimentation `lpos` method in class `org.springframework.data.redis.connection.DefaultedRedisConnection`, which
will cause `StackOverflowError` when calling "connection.lpos()".
I tried to fix it in this PR and tested on my computer. 
Thanks for your time.
=> Fixed - RedissonConnection add lpos command

redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java, redisson/src/test/java/org/redisson/RedissonPermitExpirableSemaphoreTest.java
Fix for issue [#4086](https://github.com/redisson/redisson/issues/4086). Checks expiry time of RedissonPermitExpirableSemaphore before releasing so that return value of releaseLock behavior is consistent  between expired and manually released locks.
=> Check expiration before release in RedissonPermitExpirableSemaphore

redisson/src/main/java/org/redisson/config/SentinelServersConfig.java
**https://github.com/redisson/redisson/issues/3948** introduced sentinel username, but forgot to copy it in copy constructor. Result: authentication with username and password is not possible because config is always copied in org.redisson.Redisson constructor.
=> SentinelServersConfig: copy username in copy constructor

redisson/src/main/java/org/redisson/RedissonBaseLock.java
The counter should start from 0. Otherwise, according to the program logic, even if the removethreadid method is called, the counter will not be reduced to 0.
Signed-off-by: why技术 <thisiswhy@outlook.com>
=> Update ExpirationEntry in RedissonBaseLock.java

redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java
I want to run Redis native commands using redisson provided low-level client. However, I see `HMGET` command is not exposed from the `RedisCommands` interface. Hence adding `HMGET` command to the `RedisCommands` interface.
=> Add HMGET command to RedisCommands interface

.github/workflows/codeql-analysis.yml, .github/workflows/maven.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

redisson-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Spring Boot 3.0 changes the way AutoConfiguration are loaded. This PR just adds the file `org.springframework.boot.autoconfigure.AutoConfiguration.imports` to support SB 3.0 _and_ SB 2.x.
No module redisson-spring-data-30 is added as the 2.7 version seems to be compatible...
#4328
=> compatibility for spring boot 3

redisson/src/test/java/org/redisson/RedissonRuntimeEnvironment.java
I faced a pah problem testing the [org.redisson.RedissonAtomicLongReactiveTest.java].
When I checked this problem, only Windows OS Path was set in RedissonRuntimeEnvironment. So I sent a PR by adding the Mac OS Path.
[problem]
[solved]
=> Added testing redis binary path for  Mac OS 

pom.xml
There is [CVE-2022-42003](https://nvd.nist.gov/vuln/detail/CVE-2022-42003) for `jackson-databind` `2.13.4`, which is fixed in the next point release `2.13.4.1`.
I didn't check if redisson is actually vulnerable. But bumping the dependency to an unaffected version will at least silence any vulnerability scanners when redisson is used.
=> Bump jackson-bom to 2.13.4.20221013 (upgrade to jackson-databind 2.13.4.2)

redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java
By overriding the objectMapper’s TypeFactory to use the default type factory, you are blowing away any type factory configuration that may have been done on the mapper eg in Jdk8Module it sets up Jdk8Types. As a result this can result in the inability to deserialize desired types that the mapper had been configured for.
This is what happened with ticket #2010
To fix this, while still using the desired ClassLoader you can just get the TypeFactory from the object mapper and then call withClassLoader on it.
=> Fix incorrectly reset jackson type factory

redisson/src/main/java/org/redisson/RedissonFuction.java, redisson/src/test/java/org/redisson/RedissonFunctionTest.java
This changes the way keys are passed to Redis in `RedissonFunction`. Currently, the `keys` list is added to `args`, rather than the contents of `keys`. This stringifies the list when it's passed to Redis, making the entire list a single key. If more than one key is passed, Redis starts to use args for keys, since it expects *n* keys. I have added a unit test covering both these cases.
See #4729 for more details.
=> Bugfix - RedissonFunction doesn't pass keys to Redis correctly

redisson/src/main/java/org/redisson/MapWriteBehindTask.java, redisson/src/main/java/org/redisson/RedissonBaseLock.java, redisson/src/main/java/org/redisson/RedissonMap.java, redisson/src/main/java/org/redisson/RedissonNode.java, redisson/src/main/java/org/redisson/RedissonReliableTopic.java, redisson/src/main/java/org/redisson/RedissonRemoteService.java, redisson/src/main/java/org/redisson/Version.java, redisson/src/main/java/org/redisson/client/RedisConnection.java, redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java, redisson/src/main/java/org/redisson/client/handler/CommandPubSubDecoder.java, redisson/src/main/java/org/redisson/client/handler/ErrorsLoggingHandler.java, redisson/src/main/java/org/redisson/client/handler/PingConnectionHandler.java, redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java, redisson/src/main/java/org/redisson/command/CommandBatchService.java, redisson/src/main/java/org/redisson/connection/DNSMonitor.java, redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java, redisson/src/main/java/org/redisson/connection/MasterSlaveEntry.java, redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java, redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java, redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java, redisson/src/main/java/org/redisson/connection/pool/ConnectionPool.java, redisson/src/main/java/org/redisson/eviction/EvictionTask.java, redisson/src/main/java/org/redisson/executor/RedissonExecutorRemoteService.java, redisson/src/main/java/org/redisson/remote/BaseRemoteProxy.java, redisson/src/test/java/org/redisson/RedissonFairLockTest.java
Changes for:
1. Late-binding message parameters
2. Grouping by message patterns in log aggregation systems
=> Use slf4j late-binding when logging instead of string concat

redisson/src/main/java/org/redisson/spring/cache/RedissonCache.java, redisson/src/main/java/org/redisson/spring/cache/RedissonCacheMetrics.java
Currently, `RedissonCache` (aka the implementation `org.springframework.cache.Cache`) supports some metrics (hits, misses, puts) but evictions are not taken into account.
=> Add evictions metrics support for RedissonCache

redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphore.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreAsync.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreReactive.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreRx.java, redisson/src/test/java/org/redisson/RedissonPermitExpirableSemaphoreTest.java
This PR implements tracking and management setting for the maximum number of permits possible for the RedissonPermitExpirableSemaphore.
The added functionality is contained in the following functions
`int maximumPermits()`: returns the maximum number of permits which could ever be available
`int claimedPermits()`: returns the number of permits which are currently claimed by clients
`boolean trySetMaximumPermits(int maximumPermits)`: increases/decreases the number of available permits such that the maximum number of permits is the provided value
=> Add tracking and setters for max permits

redisson/src/main/java/org/redisson/client/handler/CommandEncoder.java
We found it failed to boot after adding redisson dependency into our springboot application. It's because we set the pub message to null just to check the connection with redis and it work well when using lettuce(the pub method we use is org.springframework.data.redis.core.RedisTemplate#convertAndSend).
=> Fixed NPE while booting when pub message set to null

redisson/src/main/java/org/redisson/config/ReplicatedServersConfig.java, redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java
In replicated mode, the ConnectionManager is checking periodically which node is the current master and does auto failover.
However, in a situation where none of the previous configured addresses points to a master of the cluster, Redisson silently keeps working without logging an error. This situation may happen for example in case of an horizontal scale up of the cluster not followed by a configuration change of the addresses. This may go undetected for a while, as the client can still read from Redis, only writes are impacted.
The proposal consist of:
- add new master detection check inside `scheduleMasterChangeCheck`, gathering the roles of each node (which was already checked in existing code), and at least log an error when the master is not found.
- add a new fail-fast …
=> feat: add auto-detection of unavailable master in replicated mode

redisson/src/main/java/org/redisson/client/protocol/decoder/MultiDecoder.java, redisson/src/main/java/org/redisson/client/protocol/decoder/ObjectMapDecoder.java, redisson/src/main/java/org/redisson/client/protocol/decoder/ObjectMapEntryReplayDecoder.java, redisson/src/main/java/org/redisson/client/protocol/decoder/ObjectMapReplayDecoder.java, redisson/src/main/java/org/redisson/client/protocol/decoder/StringMapReplayDecoder.java
We are seeing a lot of allocations coming from `ObjectMapReplyDecoder` in production. The culprit is `LinkedHashMap.resize()`.
The map is currently sized with `parts.size()\2`, but doesn't take the default load factor of the map into account. This PR uses the same approach as [Guava](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Maps.java#L286) to prevent additional resizes.
Is there a utility class where the sizing logic could be centralized? I'm not very happy about the code duplication.
=> Initialize LinkedHashMap with correct initial size to avoid resizing

redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java
If the specific key in name2entry is not removed, it will cause a memory leak. Please review.
=> fix: cause of memory leak name2entry

redisson/src/main/java/org/redisson/RedissonLock.java, redisson/src/main/java/org/redisson/reactive/ReactiveProxyBuilder.java, redisson/src/test/java/org/redisson/RedissonDequeReactiveTest.java
Remove unnecessary generic type definition in RedissonLock.java to make code clean.
Fix ClassCastException from MonoNext to Flux in ReactiveProxyBuilder
=> Fix ClassCastException from MonoNext to Flux

redisson/src/main/java/org/redisson/executor/TasksRunnerService.java, redisson/src/test/java/org/redisson/executor/RedissonScheduledExecutorServiceTest.java
This pull request addresses #5148 .
I made the following changes:
- Change the order of code statements, in order to execute Runnable before scheduling next execution.
- Add 2 unit test cases, referencing `testCancelAndInterruptWithFixedDelay` as an example.
With these changes, when we cancel cron tasks, they can be successfully interrupted. (I verified it on my local machine.)
=> Bug fix: #5148

redisson/pom.xml, redisson/src/main/java/org/redisson/config/TransportMode.java, redisson/src/main/java/org/redisson/connection/ServiceManager.java
- add `TransportMode.IO_URING`
- add incubator uring dependency
Fixes and closes #5169
=> Feature - Netty native transport for `io_uring`

redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java
During warmup we call `ByteBuf.release` after decoding the value, however, the decoding action can fail which will lead to a memory leak so we move the ByteBuf release method to a `finally` block.
=> Fix possible memory leak in JsonJacksonCodec during warmup

redisson/src/main/java/org/redisson/client/handler/CommandEncoder.java
Profiling our application showed that most of our allocations, over 11% of the total allocation in our application is happening in `org/redisson/client/handler/CommandEncoder.writeArgument` in the `Long.toString` method which allocates both string and byte array.
From what I understand from the code the cases where we call `writeArgument` the arguments are quite small so caching up to 100k should be enough to cover all (?) cases, I'm guessing we can make this configurable but I'm not sure if it's a good idea.
I would've added some benchmarks if I knew where to find such.
=> Cache Long as strings in CommandEncoder in order to reduce allocations and improve performance

redisson/src/main/java/org/redisson/pubsub/CountDownLatchPubSub.java, redisson/src/test/java/org/redisson/pubsub/CountDownLatchPubSubTest.java
Previously when `RCountDownLatch` counts down to 0 and there are multiple listeners waiting on the completion, only the first listener associated with a `RedissonCountDownLatchEntry` would be notified. This change notifies all listeners in the `RedissonCountDownLatchEntry` `listeners` queue.
https://github.com/redisson/redisson/issues/5349
=> Fix RCountDownLatch only notifying the first async listener after countdown reaches 0

redisson/src/main/java/org/redisson/RedissonLock.java
In the methods tryAcquireAsync and tryAcquireOnceAsync, when leaseTime<=0, the waitTime with the original time unit is passed in without tranforming with the new timeunit TimeUnit.MILLISECONDS.
=> Fixes waitTime loses unit when passed to tryLockInnerAsync

redisson-quarkus/redisson-quarkus-30/deployment/src/main/java/io/quarkus/redisson/client/deployment/QuarkusRedissonClientProcessor.java, redisson-quarkus/redisson-quarkus-30/integration-tests/src/main/java/org/redisson/quarkus/client/it/QuarkusRedissonClientResource.java, redisson-quarkus/redisson-quarkus-30/integration-tests/src/test/java/org/redisson/quarkus/client/it/QuarkusRedissonClientResourceTest.java
When compile to Quarkus Native. Bucket delete in reactive shows method not found
After looking at the reflection output of the build, found certain methods to be missing.
Tested these configurations to be working with Bucket Delete
=> Missing methods in Quarkus Native

redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java
Make sure that the total time of shutdown() does not exceed the provided timeout.
Signed-off-by: Dave Golombek
5370
=> ConnectionManger.shutdown completes within timeout

redisson/src/main/java/org/redisson/RedissonRemoteService.java
Log exception when can't process the remote service request, like when codec can't unmarshall the RemoteServiceRequest (eg: when using Typed/JsonJacksonCodec).
Closed bug #4163 has root on this, not entering this whenComplete [section](https://github.com/redisson/redisson/blob/c792670a2e3cdcf5e51279d46ccefbdf617c1fee/redisson/src/main/java/org/redisson/RedissonRemoteService.java#L237).
=> Log swallowed exceptions in RedissonRemoteService

redisson/src/main/java/org/redisson/RedissonRemoteService.java
Reverts redisson/redisson#5427
Sorry, but `addFuture.whenComplete()` already has exception handler
=> Revert "Log swallowed exception in RedissonRemoteService sending request ack"

redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java, redisson/src/test/java/org/redisson/codec/JsonJacksonCodecTest.java
This fixes issue: #5369
The serialization of Throwable instances would fail on Java17 with error:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `java.lang.Throwable`: Failed to call `setAccess()` on Field 'detailMessage' (of class `java.lang.Throwable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @32eff876
//...
Caused by: java.lang.IllegalArgumentException: Failed to call `setAccess()` on Field 'detailMessage' (of class `java.lang.Throwable`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make field private java.lang.String …
```
=> Fix: JsonJacksonCodec fails to serialize Throwable on Java17

redisson/src/main/java/org/redisson/RedissonBaseLock.java, redisson/src/main/java/org/redisson/RedissonMultiLock.java, redisson/src/main/java/org/redisson/api/RLockAsync.java, redisson/src/main/java/org/redisson/api/RLockReactive.java, redisson/src/main/java/org/redisson/api/RLockRx.java, redisson/src/test/java/org/redisson/RedissonLockReactiveTest.java, redisson/src/test/java/org/redisson/RedissonLockRxTest.java
We can acquire a lock for a given threadId using methods like `Mono<Boolean> tryLock(long threadId)`.
But we can't check, if a lock is held by a given threadId for reactive API.
We already  have the method `boolean isHeldByThread(long threadId)` in RLock.
Adding similar method to RLockReactive: `Mono<Boolean> isHeldByThread(long threadId);`
=> Add isHeldByThread(long threadId) to RLockReactive

redisson/src/main/java/org/redisson/RedissonSetCache.java
This PR fixes the issue with the incorrect zadd parameter in `RedissonSetCache`'s `addIfAbsentAsync` method. `zadd` incorrectly used `ARGV[1]` instead of `ARGV[3]`, resulting in the data not being stored correctly in the set.
The issue also affected `addIfAbsent`.
=> Fix - RedissonSetCache.addIfAbsentAsync used incorrect argument for zadd

redisson/src/main/java/org/redisson/codec/Kryo5Codec.java, redisson/src/test/java/org/redisson/codec/Kryo5CodecTest.java
This PR fixes the bug that the `Kryo5Codec` constructor is ignoring the custom classloader. 
We observed that using a custom ClassLoader for integration tests that we got a `ClassCastException` with two different Classloaders in place even though we provided only our custom one. 
This PR is based on the discussion in  #5579, especially https://github.com/redisson/redisson/issues/5579#issuecomment-1970845929.
=> Fixed Kryo5Codec constructor ignores custom ClassLoader

redisson/src/main/java/org/redisson/transaction/BaseTransactionalSet.java, redisson/src/test/java/org/redisson/RedissonSetTest.java
Fix issue #5728 - resource leak error when executing multiple contains operation of RSet in transaction
=> Fix issue #5728 - Executing multiple RSet.add and RSet.contains methods within the same transaction results in the LEAK error

redisson/pom.xml
The jmockit version is set to 1.52.0 in the redisson-parent pom.xml.
However, inside maven-surefire-plugin, version 1.51.0 were being used.
So I got issued that mvn can not find jmockit that version 1.51.0 when I executing mvn test.
Therefore, I have updated all stuff that used in jmockit javaagent version to target 1.52.0.
Below are the log messages I got.
```
Error occurred during initialization of VM
agent library failed Agent_OnLoad: instrument
Error opening zip file or JAR manifest missing : /Users/aronroh/.m2/repository/com/github/hazendaz/jmockit/jmockit/1.51.0/jmockit-1.51.0.jar
```
=> Modify jmockit mvn version to 1.52.0 that used in maven-surefire-plugin

redisson/src/main/java/org/redisson/client/RedisNoReplicasException.java, redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java
* During a failover event where a new redis master is being promoted there is a period of time before the slaves begin to follow the new master. This can lead to write calls failing with NOREPLICAS. This usually happens when min-slaves-to-write is configured as non 0.
* This error could occur for a misconfiguration, and reties wouldnt help, but we have found that in practice we see failed writes on most failovers due to this error, and a treating it as retryable would have prevented those exception cases.
Scenarios for reproduction:
1. Create a 3 redis 3 sentinel setup, and configure min-slaves-to-write.
2. Create a client which continually fires off write request to redis
3. Kill off the redis listed as master
4. Observe that NOREPLICAS error is thrown, and the write call fails without …
=> Allow retry of NOREPLICAS error

redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java, redisson/src/test/java/org/redisson/RedissonTest.java
See details here:
https://github.com/redisson/redisson/issues/5795#issuecomment-2107851479
I wasn't able to run successful unit tests locally on master, following this guide:
https://github.com/redisson/redisson/blob/7b29c420dee37977c5ca6f827a7205205d29b389/.github/CONTRIBUTING.md
New test fails before change and works with the change.
=> Correctly update shutdown timeout after each step in connection manager shutdown

redisson/src/main/java/org/redisson/command/RedisQueuedBatchExecutor.java
1. use redis-cli "set test test"
2. run the code
`
RBatch batch = client.createBatch(BatchOptions.defaults().executionMode(ExecutionMode.REDIS_WRITE_ATOMIC));
batch.getAtomicLong("test").incrementAndGetAsync();
batch.executeAsync();
`
that will cause RedisException, than the connection that 'batch' used will not release.
=> Fixed - releaseConnection may not execute correctly

redisson/src/main/java/org/redisson/transaction/RedissonTransactionalBucket.java, redisson/src/test/java/org/redisson/transaction/RedissonTransactionalBucketTest.java
More information:
https://github.com/redisson/redisson/issues/5561
=> TransactionalBucket#set(V, Duration), PSETEX is called before MULTI

redisson/src/main/java/org/redisson/RedissonBaseLock.java
in mehod scheduleExpirationRenewal
oldEntry.addThreadId may happen before entry.addThreadId
=> Fixed - Concurrency problem

redisson/src/test/java/org/redisson/RedissonRemoteServiceTest.java
Added testCancelRxJava to demonstrate issue #5498
=> RemoteService execution cancellation does not work with RxJava3 implementation 

redisson/src/main/java/org/redisson/RedissonSearch.java, redisson/src/test/java/org/redisson/RedissonSearchTest.java
when create index , parameters passed in the wrong order.
refer to :
[RediSearch param sequence](https://github.com/RediSearch/RediSearch/blob/v2.8.14/src/spec.c#L876)
=> Fixed - Redisearch parse params error

redisson/src/main/java/org/redisson/RedissonRingBuffer.java, redisson/src/test/java/org/redisson/RedissonRingBufferTest.java
RingBuffer
start with capacit(3) and values of {0, 1, 2}, after reset capacity to 5, the list should persist values {0, 1, 2}, not {1, 2}
=> Fixed - RingBuffer#setCapacity, trim list incorrect

redisson/src/main/java/org/redisson/RedissonBinaryStream.java, redisson/src/test/java/org/redisson/RedissonBinaryStreamTest.java
1. As the interface(SeekableByteChannel) defined : throws IllegalArgumentException If the new size is negative
2. if the new size is zero, size of the `string` object should be zero
=> Fixed - SeekableByteChannel#truncate method

redisson/src/main/java/org/redisson/RedissonMap.java, redisson/src/test/java/org/redisson/BaseMapTest.java
Fixes a bug introduced in Redisson 3.32.0
`RedissonMap.computeAsync` doesn't seem to store the computed value if there is no previously set value for the given key.
=> Fix computeAsync for empty keys

redisson/src/main/java/org/redisson/pubsub/PublishSubscribe.java, redisson/src/test/java/org/redisson/pubsub/PublishSubscribeTest.java
I got RedisTimeoutException while calling RedissonLock.tryLock function. After this exception, 'tryLock' call on same key failed with exactly same exception and message.
```
2024-07-19T10:40:05.638Z ERROR 1 --- [tContainer#13-7] org.redisson.RedissonLock                : org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 13ms. Try to increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.\
\
java.util.concurrent.ExecutionException: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 13ms. Try to increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.\
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)\
at …
```
=> Fixed 'race condition' while calling tryLock function

redisson/src/main/java/org/redisson/RedissonMapCacheNative.java
When attempting to listen for Map expiration fields, it will only return events of a new TTL field set. What this means is that I cannot get the event whenever an actual field in a MapCacheNative has expired natively.
The following is the Sub/Pub message I get when a hset field has expired:
For every `map.put("key", "value", Duration.of(30))`, I will get a MapExpiredListener fired. Supposedly MapExpiredListener should only be fired when a hash field has expired. Not when the hash field expiration is set. You can test this out with the following code:
```java
RedissonClient redissonClient = ...
RMapCacheNative<String, String> map = redissonClient.getMapCacheNative("gs_server_data");
map.addListener((MapExpiredListener) name -> {
// Check the map, the field is still there, yet this event is …
```
=> Fix RMapCacheNative expiring keyspace event using the wrong key

redisson/src/main/java/org/redisson/RedissonSubList.java, redisson/src/test/java/org/redisson/RedissonListTest.java
Currently, the two methods `lastIndexOfAsync` and `removeAllAsync` of the SubList do not perform as expected.
It will caused a RedisException when execute lua-script
=> Fixed - caused RedisException when execute lua-script

redisson/src/main/java/org/redisson/api/RLiveObjectService.java
The description of the return value is incorrect.
The return value of detach method of the RLiveObjectService interface is not proxied object.
=> Fix - the description of the return for the RLiveObjectService interface

redisson/src/main/java/org/redisson/RedissonExecutorService.java
When wrapping an OutputStream around a ByteArrayOutputStream, it is safer
to flush. See, for example,
https://stackoverflow.com/questions/2984538/how-to-use-bytearrayoutputstream-and-dataoutputstream-simultaneously-java
=> Fix in RedissonExecutorService

redisson/src/main/java/org/redisson/RedissonMap.java
Inside computeIfAbsent() in RedissonMap, lock is being taken for the entire operation, however we don't need the lock if value is already present, in which case get() operation doesn't need a lock.
This gives a significant performance boost since we avoid distributed lock since most of the times value will be present.
Have also retained the original get() operation inside the lock because value may have been computed by the previous lock holder.
=> Optimization: Don't take lock in computeIfAbsent if only get is needed

redisson/src/main/java/org/redisson/api/search/index/IndexInfo.java, redisson/src/main/java/org/redisson/client/protocol/decoder/IndexInfoDecoder.java
Follow-up to #5950
Redisson 3.34.1
Redisearch 2.8.8
Redis 6.2.13
The problem remains for other non-explicitly integer fields. Personally encountered on (erroneous) output of
```
15) num_records
16) "1.8446744073709543e+19"
```
but since all those fields can technically have scientific notion and can become unrepresentable in Java signed long (the value in this case is approaching 2^64 and would become -9223372036854767192) even if only in case of redisearch errors, it would be prudent to reflect that in data types.
=> Redisearch FT.INFO result decoder throws NumberFormatException

redisson/src/main/java/org/redisson/RedissonObject.java, redisson/src/test/java/org/redisson/RedisDockerTest.java, redisson/src/test/java/org/redisson/RedissonBucketTest.java, redisson/src/test/java/org/redisson/RedissonIdGeneratorTest.java
1. RedissonBucketTest#testCopy3:  
completion test case which replication across different dbs.
2. RedissonBucketTest#testCopy4:  
copy the key `test`(db1) to the target key `test`(db0): 
this case shows after `copy` command executed, the result is not match expectations. db0 did not have the key `test`.
3. RedissonIdGeneratorTest#testCopy: 
when the lua script in copy method executed, the number of keys in the source database is incorrect.
=> Improvement - Copy command execute through multi db

redisson/src/main/java/org/redisson/codec/FuryCodec.java
Add zero-copy serialization/deserializaiton for fury codec:
- `MemoryBuffer` in Fury can wrap off-heap buffer directly, by converting `ByteBuf` in netty to `ByteBuffer`, we can wrap the memory into Fury `MemoryBuffer`, then the deserialization can avoid copying to heap buffer.
- Wrap `ByteBufAllocator.DEFAULT.buffer()` into fury buffer directly, if the remaining buffer are enough for object serialization, we can save a copy.
=> wrap ByteBuf into Fury Buffer for zero-copy deserialization

redisson-spring-data/redisson-spring-data-32/pom.xml, redisson-spring-data/redisson-spring-data-33/pom.xml, redisson/pom.xml
Keep the jmockit version in the plugin consistent with that in the dependencies.
Jmockit version in dependencies is 1.54.0, but is 1.52.0 in plugin.
=> Fixed - upgrade Jmockit version to 1.54.0

redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-24/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-24/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-25/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-25/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-26/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-26/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-27/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-27/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-30/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-30/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-31/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-31/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-32/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-32/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java, redisson-spring-data/redisson-spring-data-33/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStreamCommands.java, redisson-spring-data/redisson-spring-data-33/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java
The xClaim command interface in Spring Data Redis takes minIdleTime as an option. However, in the current implementation of xClaim in Redisson, it validates idleTime instead of minIdleTime, which causes a NullPointerException (NPE).
This PR fixes the validation to properly handle minIdleTime.
issue: https://github.com/redisson/redisson/issues/6192
=> fixed - xcaim method should verify minIdleTime not idleTime

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java, redisson/src/main/java/org/redisson/api/LocalCachedMapOptions.java, redisson/src/main/java/org/redisson/cache/AbstractCacheMap.java, redisson/src/main/java/org/redisson/cache/LocalCacheListener.java, redisson/src/main/java/org/redisson/cache/LocalCacheView.java
This will help to increase the performance of RedissonLocalCachedMap by introducing a cache synonym on `LocalCacheView.toCacheKey(Object)`  method.
Changes:
- Add new config `LocalCachedMapOptions.storeCacheKey` that defines whether to store CacheKey of an object key into the local cache.
- Create a new local cache for caching CacheKey purpose
- Inside `LocalCacheView.toCacheKey(Object)`:
- Check if the Object already has Its CacheKey, and return the cached value.
- If the Object does not have its CacheKey, create a new CacheKey put it into the local cache, and return it.
=> Support to cache method LocalCacheView.toCacheKey(Object) for CacheProvider.REDISSON

redisson/src/main/java/org/redisson/client/protocol/decoder/IndexInfoDecoder.java
Follow-up to #6090 and #5950
Redisson 3.37
Redisearch 7.99.00
Redis 8.0-M01 (cluster configuration)
Sometimes FT.INFO returns inf (and -inf might be likely too), causing current parser to throw:
```
java.lang.NumberFormatException: For input string: "inf"
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
at java.base/java.lang.Double.parseDouble(Unknown Source)
at java.base/java.lang.Double.valueOf(Unknown Source)
at org.redisson.client.protocol.decoder.IndexInfoDecoder.toDouble(IndexInfoDecoder.java:95)
at org.redisson.client.protocol.decoder.IndexInfoDecoder.decode(IndexInfoDecoder.java:60)
```
=> Redisearch FT.INFO result decoder throws on infinity values

redisson/src/main/java/org/redisson/RedissonRateLimiter.java, redisson/src/main/java/org/redisson/api/RRateLimiter.java, redisson/src/test/java/org/redisson/RedissonRateLimiterTest.java
The parameter timeToLive  should be keepAliveTime  in RRateLimiter.
```
limiter.trySetRate(RateType.OVERALL, 1, Duration.ofMinutes(1), Duration.ofMinutes(5));
```
In this code, if no accquire has been invoked, it will be deleted in 5 miniute, if accquire be invoked it will reset ttl to 5 miniutes.
Just set ttl as timeToLive directly,  that's does not conform with business scenario mostly.
=> Improvement - Change timeToLive to keepAliveTime #6216

redisson/src/main/java/org/redisson/RedissonBatch.java, redisson/src/main/java/org/redisson/RedissonSearch.java, redisson/src/main/java/org/redisson/api/RBatch.java, redisson/src/main/java/org/redisson/api/RBatchReactive.java, redisson/src/main/java/org/redisson/api/RBatchRx.java, redisson/src/main/java/org/redisson/reactive/RedissonBatchReactive.java, redisson/src/main/java/org/redisson/rx/RedissonBatchRx.java
Adds the missing `getSearch(...)` methods to `RBatch`, `RBatchReactive` and `RBatchRx` so that search commands can be used with pipelining. Fixes #6125.
=> Make search available via batch (pipelining). Fixes #6125.

redisson/pom.xml
This PR upgrades the version of kryo from 5.6.1 to 5.6.2 in the project’s pom.xml file. The change is necessary because kryo version 5.6.1 was accidentally compiled for Java 17, which is not compatible with Java 8 environments.
```
<dependency>
<groupId>com.esotericsoftware</groupId>
<artifactId>kryo</artifactId>
<version>5.6.2</version>
</dependency>
```
According to the [Kryo release notes](https://github.com/EsotericSoftware/kryo/releases), version 5.6.1 was mistakenly targeted for Java 17, which causes compatibility issues for projects still using Java 8. Upgrading to version 5.6.2 resolves this issue, as it reverts the target Java version to a more compatible setting.
Testing:
•	Built the project to ensure compatibility with Java 8.
•	Ran existing tests to confirm no regression or …
=> Upgrade kryo version to 5.6.2 for Java 8 compatibility

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java, redisson/src/main/java/org/redisson/cache/LocalCacheView.java
If `useObjectAsCacheKey=true` and `cacheSize = 0`, LocalCacheView will cache every cacheKey although the keys are unavailable in the cache and all unavailable keys will not be removed. This will make memory leak.
Example code:
```
Random random = new Random();
RLocalCachedMap<Object, Object> localCachedMap = client.getLocalCachedMap("test-cache", new KryoCodec(List.of(Object.class)), LocalCachedMapOptions.defaults()
.evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
.cacheSize(0)
.syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE)
.useObjectAsCacheKey(true));
while (true) {
localCachedMap.get(random.nextInt()); //potential memory leak
}
```
Solution: Just only cache cacheKey for available keys in the cache
=> Fix potential memory leak on method LocalCacheView.toCacheKey if useObjectAsCacheKey = true

redisson/src/main/java/org/redisson/executor/TasksRunnerService.java, redisson/src/test/java/org/redisson/executor/RedissonScheduledExecutorServiceTest.java, redisson/src/test/java/org/redisson/executor/SwallowingInterruptionTask.java
In `TasksRunnerService`, the behaviors of FixedRate and FixedDelay are quite different.
In method `scheduleWithFixedDelay`, we (1) execute `Runnable`, and then (2) check whether the task request id still exists, and finally (3) schedule next execution.
However, in method `scheduleAtFixedRate`, we (1) execute `Runnable`, and then (2) schedule next execution, without checking the task request id.
I believe that `FixedDelay` and `FixedRate` are similar and should not have such difference, so I raise this pull request to add a check in method `scheduleAtFixedRate`.
This pull request also addresses issue #5143 .
=> Code Review - Behaviors of FixedRate and FixedDelay should be similar in TasksRunnerService

redisson/src/main/java/org/redisson/RedissonBitSet.java, redisson/src/test/java/org/redisson/RedissonBitSetTest.java
the method ` lengthAsync` of `RedissonBitSet` return unexpected value or caused RedisException in some case.
=> Fixed - method lengthAsync of RedissonBitSet

redisson/src/main/java/org/redisson/RedissonListMultimap.java, redisson/src/main/java/org/redisson/RedissonSetMultimap.java, redisson/src/main/java/org/redisson/api/RMultimap.java, redisson/src/main/java/org/redisson/api/RMultimapAsync.java, redisson/src/main/java/org/redisson/api/RMultimapReactive.java, redisson/src/main/java/org/redisson/api/RMultimapRx.java, redisson/src/test/java/org/redisson/RedissonListMultimapTest.java, redisson/src/test/java/org/redisson/RedissonSetMultimapTest.java
Is faster than replaceValues and replaceValuesAsync by not returning the new values.
Closes #6294.
=> Add fastReplaceValuesAsync and fastReplaceValues to RMultimap and its implementations.

redisson/src/main/java/org/redisson/config/PropertiesConvertor.java
Similar to https://github.com/redisson/redisson/issues/4076 config load
fails for `sentinel-addresses`. This adds sentinel to the LIST_NODES so
that sentinel configuration also works.
Signed-off-by: Benjamin Nørgaard <mail@blacksails.dev>
=> Fix Quarkus redisson config with sentinel config

redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java, redisson/src/test/java/org/redisson/RedissonPermitExpirableSemaphoreTest.java
[issues/6343](https://github.com/redisson/redisson/issues/6343)
For the caller, if they first acquire 2 permits with leasetime, then acquire 3 permits without leasetime limit , and finally want to release these 5 permits at once, but they fail because the first two permits have expired. It will affect the caller's previous usage logic of this method. Is this okay, or is this something the caller should consider?
=> Fixed - RPermitExpirableSemaphore.release

redisson/src/main/java/org/redisson/misc/ProxyBuilder.java, redisson/src/main/java/org/redisson/reactive/RedissonListMultimapReactive.java, redisson/src/test/java/org/redisson/BaseReactiveTest.java, redisson/src/test/java/org/redisson/RedissonReactiveListMultimapTest.java
This change resolves several issues related to invoking `RListReactive` interface methods on the return value of `RedissonListMultiMapReactive.get(K key)`, including #6355.
For a reason that I could not find, `ProxyBuilder` gets `IllegalAccessException` on line 54 for `RedissonListMultiMap.removeAllAsync(Object key)`:
```
Callable<RFuture<Object>> callable = () -> (RFuture<Object>) instanceMethod.invoke(instance, args);
```
Due to that I needed to add this as a band-aid solution:
```
instanceMethod.setAccessible(true);
```
If someone could figure out the root cause it would be great, but I don't think that's a blocker for the fix.
=> bugfix: RedissonListMultimapReactive.get(K) was using the wrong instance for creating proxy

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
The Sentinel logic for checking if the `master` has changed (as per `Config#scanInterval`) resolves the URI returned by the `SENTINEL GET-MASTER-ADDR-BY-NAME` to an IP address. This resolution would ignore configured `NatMapper`, thus potentially ignoring changes to the `host`.
Example, if the current master responds with:
```
SENTINEL GET-PRIMARY-ADDR-BY-NAME myprimary
1) "valkey-node-2.valkey-headless.default.svc.cluster.local"
2) "6379"
```
Configured `NatMapper` would map `redis://valkey-node-2.valkey-headless.default.svc.cluster.local:6379` to `redis://localhost:1112`. But because it was not used in the `checkMasterChange` procedure, it would try to resolve hostname `valkey-node-2.valkey-headless.default.svc.cluster.local`, which fails.
`serviceManager.resolveIP(scheme, u)` does not …
=> fix: resolve Sentinel master change through NAT

redisson/src/test/java/org/redisson/RedissonLockTest.java
[issues/6202](https://github.com/redisson/redisson/issues/6202)
=> Fixed - Run RedissonLockTest.testLockUninterruptibly then run RedissonLockTest.testSubscriptionsPerConnection will test failed.

redisson/src/main/java/org/redisson/command/RedisExecutor.java
Fix incorrect errors like:
```
Redis server response timeout (3000 ms) occured after 0of 3 retry attempts, is non-idempotent command: false
```
=> Fix the "of" string literal in RedisExecutor exceptions

redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSession.java, redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-10/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java, redisson-tomcat/redisson-tomcat-10/src/test/java/org/redisson/tomcat/TestServlet.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSession.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-11/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java, redisson-tomcat/redisson-tomcat-11/src/test/java/org/redisson/tomcat/TestServlet.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSession.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java, redisson-tomcat/redisson-tomcat-7/src/test/java/org/redisson/tomcat/TestServlet.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java, redisson-tomcat/redisson-tomcat-8/src/test/java/org/redisson/tomcat/TestServlet.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSession.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java, redisson-tomcat/redisson-tomcat-9/src/test/java/org/redisson/tomcat/TestServlet.java
[issues/6232](https://github.com/redisson/redisson/issues/6232)
=> Fixed - Inconsistent MaxInactiveInterval Setting in Sessions in multi-node

redisson/src/main/java/org/redisson/RedissonRateLimiter.java
Improvement - Add check, The parameter keepAliveTime should be greater than or equal to rateInterval
Here are the reasons:
If the expiration time is less than the time window, the data will be deleted in advance, the actual statistical time of the time window will be shortened, and the request cannot be correctly counted, triggering misjudgment or missed judgment.
Example:
Assuming the expiration time is 0.6 seconds, the time window is 1 second, and the limit is 3 times, the first request is at 0 seconds, the second request is at 0.1 seconds, and the third request is at 0.2 seconds. At this time, there is no request until 0.8 seconds, then zset will expire, and the fourth request is at 0.9 seconds. Since zset has been deleted, there is only the fourth request from 0 to 0.9 seconds, so …
=> Improvement - Add check, The parameter keepAliveTime should be greater than or equal to rateInterval

redisson/src/main/java/org/redisson/codec/Kryo5Codec.java, redisson/src/test/java/org/redisson/codec/Kryo5CodecTest.java
Currently AtomicBoolean, AtomicInteger, AtomicLong and AtomicReference are not supported by the Kryo5Codec. However, the kryo lib supplies serializers for those classes. This patch registers those serializers in Kryo5Codec.
=> Add support for atomic objects in Kryo5Codec

docs/data-and-services/objects.md
Added the missing `"` in the BitSet example code.
=> fix typo in BitSet docs

docs/data-and-services/collections.md
Fixes typo in the Java code for using `DelayedQueue`
=> Fix typo in delayed queue code example

redisson/src/main/java/org/redisson/config/Config.java
Dear Redisson team,
I'm not sure if this was intentional, but the `ReplicatedServersConfig config` parameter passed to the function wasn't being used anywhere else. I've checked the code usage and it was used by `#useReplicatedServers` method only so I think it was supposed to assign to `replicatedServersConfig` property.
If this was designed intentionally by the team, feel free to close this pull request.
Best regards,
=> Fix unused server config

redisson/src/main/java/org/redisson/RedissonMapCache.java
Fix: Correct assignment logic for removal operations(set value → null, existing value → oldValue) During removal, the 'value' should be set to null, while the existing non-null value should be assigned to 'oldValue'.
=> Fix: Correct assignment logic for removal operations

docs/web-session-management.md, redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java
Add support for Tomcat SSO. Solves https://github.com/redisson/redisson/issues/5603.
Currently when you try to use SSO available in Tomcat it is stored only locally, not through Redisson within Redis.
This adds custom Valve that extends the one provided by Tomcat to use Redis storage instead.
It is based on previous PR for the same functionality: https://github.com/redisson/redisson/pull/6404.
In comparison to previous PR it tries to make the least possible duplication of code with Tomcat's `SingleSignOn` implementation.
Also replaced `redissonClient.getMap()` with `RedissonSessionManager.getMap()` as recommended in  https://github.com/redisson/redisson/discussions/5657#discussioncomment-8618158.
Confirmed locally that with those changes SSO works when different applications are deployed …
=> Add support for Tomcat SSO

redisson/src/main/java/org/redisson/misc/RedisURI.java, redisson/src/test/java/org/redisson/misc/RedisURITest.java
Redis CLI supports URI syntax in form `redis://auth@host:port` and uses single component not as username (as stated in RFC 1738) but as a token, and sends "AUTH auth" command to server. This commit makes the RedisURI parse to accept single auth component in URI as password and, thus, successfully authenticate client
=> Make RedisURI behavior equal to Redis CLI

redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java
In some specific situations session manager might have been set before logger is initialized.
When using changes from https://github.com/redisson/redisson/pull/6639 we have found out that it might fail with NPE.
For example when deployed into TomEE some (not all) applications from EAR triggered it. Confirmed that with following fix it works as expected.
Appearantly `RedissonSingleSignOn.setSessionManager()` may be called before `ValveBase.initInternal()` (super super of RedissonSingleSignOn) is called resulting into `containerLog` not being initialized yet.
Keeping logging in other methods (all of them are overrides or called from those overrides) without changes as it is used exactly the same way also in super class. Which means those methods should not be called before `initInternal()`.
=> Prevent NPE in Tomcat SSO in specific situations

redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java
Potential fix for [https://github.com/redisson/redisson/security/code-scanning/12](https://github.com/redisson/redisson/security/code-scanning/12)
To fix the issue, the type of the variable `i` should be widened to match the type of `size`, which is `long`. This ensures that the comparison `i < size` is between two values of the same type, avoiding overflow and ensuring the loop behaves as intended.
**Steps to implement the fix:**
1. Change the type of the loop variable `i` from `int` to `long` in both loops (lines 506 and 518).
2. Ensure that all operations involving `i` within the loop are compatible with the `long` type.
No additional imports, methods, or definitions are required for this fix.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 12: Comparison of narrow type with wide type in loop condition

redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSingleSignOn.java
Make sure that when working with some SSO entry it is synchronized between local and remote cache.
When using changes from https://github.com/redisson/redisson/pull/6639 we have found out that when SSO entry is removed by one application server and then it is sent in request to another where it is cached locally it fails with NPE.
Now when it is working with SSO entry it always makes sure that data in remote and local cache for the ID are the same. Using the remote cache in Redis or Valkey the primary one.
It also made all the overrides even simpler.
=> Better synchronization of remote and local Tomcat SSO cache

redisson/src/main/java/org/redisson/command/CommandAsyncService.java, redisson/src/test/java/org/redisson/RedissonScriptTest.java
Fixed command map will be abnormal when script has two identical commands, and the strings that replace these two commands include themselves . #6666
=> Fixed command map. #6666

redisson/src/main/java/org/redisson/PubSubEntry.java, redisson/src/main/java/org/redisson/RedissonCountDownLatchEntry.java, redisson/src/main/java/org/redisson/RedissonLockEntry.java, redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java, redisson/src/main/java/org/redisson/pubsub/PublishSubscribe.java, redisson/src/test/java/org/redisson/RedissonPermitExpirableSemaphoreTest.java
Fixed RedissonPermitExpirableSemaphore.tryAcquire will fail when multiple threads acquire multiple permits at the same time.  #6664
=> #6664 Fixed RedissonPermitExpirableSemaphore.tryAcquire will fail when multiple threads acquire multiple permits at the same time. 

redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-11/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
a follow up for https://github.com/redisson/redisson/pull/6179 where get/setConfig methods were not added for tomcat 10 & 11
=> add missing get/set config object for tomcat 10 & 11

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
#6679 
Read method in RedissonLocalCachedMap don't release ByteBuf, and there is no need to encodeMapKey when use LOCALCACHE
=>  Fixed - Read method in RedissonLocalCachedMap don't release ByteBuf #6679

redisson/src/main/java/org/redisson/RedissonRemoteService.java
[issues/6727](https://github.com/redisson/redisson/issues/6727)
=> Fixed - RScheduledExecutorService throws exception on deregisterWorkers() #6727

redisson/src/main/java/org/redisson/connection/ConnectionsHolder.java
Proposition to solve the issue #5151 (and #6765) by using a deque for free connections to reuse recent connections and allow idle connection release
=> Connection pool should prioritize recently used connections to ease idle connection discard #5151
