src/main/java/org/redisson/Redisson.java, src/main/java/org/redisson/RedissonClient.java, src/main/java/org/redisson/codec/JsonJacksonCodec.java, src/test/java/org/redisson/RedissonBucketTest.java
(https://github.com/mrniko/redisson/issues/125)
See issue #125
=> Implement getBuckets(String pattern) #125

src/main/java/org/redisson/codec/KryoCodec.java
(https://github.com/mrniko/redisson/issues/127)
=> KryoCodec: do not encode / decode keys #127

src/main/java/org/redisson/Redisson.java, src/main/java/org/redisson/RedissonBlockingQueue.java, src/main/java/org/redisson/RedissonClient.java, src/main/java/org/redisson/core/RBlockingQueue.java, src/test/java/org/redisson/RedissonBlockingQueueTest.java
I have more test cases to cover but here is the general idea in addressing #117  . You might have some feedback already but please do not merge yet.
=> Initial attempt at blocking queue (WIP)

src/main/java/com/lambdaworks/redis/pubsub/RedisPubSubConnection.java, src/main/java/org/redisson/RedisPubSubTopicListenerWrapper.java, src/main/java/org/redisson/RedissonTopic.java, src/main/java/org/redisson/connection/ConnectionManager.java, src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java, src/main/java/org/redisson/connection/PubSubConnectionEntry.java, src/main/java/org/redisson/core/RTopic.java, src/test/java/org/redisson/RedissonTopicPatternTest.java
Implemented pubsub wildcard support by adding new interface methods and backing methods down through the class hierarchy
=> #76 - added support for pubsub wildcard topics

src/main/java/org/redisson/BaseConfig.java
this builds upon pull req #177 and adds a line that's needed for this to work
=> allow for naming connections

src/main/java/org/redisson/RedissonCountDownLatch.java, src/main/java/org/redisson/RedissonLock.java, src/main/java/org/redisson/client/protocol/RedisCommands.java, src/main/java/org/redisson/client/protocol/RedisStrictCommand.java, src/test/java/org/redisson/BaseTest.java, src/test/java/org/redisson/RedissonTwoLockedThread.java
=> fix issue EOFException when I use RLock with SerializationCodec #254

pom.xml, src/main/java/org/redisson/codec/CborJacksonCodec.java, src/main/java/org/redisson/codec/JsonJacksonCodec.java, src/test/java/org/redisson/RedissonCodecTest.java
cbor it's like JSON. but fast and small.
See <http://cbor.io/>.
=> Add support for cbor (http://cbor.io/) codec

src/main/java/org/redisson/RedissonLexSortedSet.java, src/main/java/org/redisson/RedissonScoredSortedSet.java, src/main/java/org/redisson/client/protocol/RedisCommands.java, src/main/java/org/redisson/connection/SentinelConnectionManager.java, src/main/java/org/redisson/core/RLexSortedSet.java, src/main/java/org/redisson/core/RLexSortedSetAsync.java, src/main/java/org/redisson/core/RScoredSortedSet.java, src/main/java/org/redisson/core/RScoredSortedSetAsync.java, src/test/java/org/redisson/RedissonScoredSortedSetTest.java
=> Revert "Revert "lexRange related methods with limit options and zrangebyscore support""

src/main/java/org/redisson/RedisNodes.java, src/main/java/org/redisson/cluster/ClusterConnectionListener.java, src/main/java/org/redisson/connection/ClientConnectionsEntry.java, src/main/java/org/redisson/connection/ConnectionListener.java, src/main/java/org/redisson/connection/ConnectionManager.java, src/main/java/org/redisson/connection/DefaultConnectionListener.java, src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java, src/main/java/org/redisson/connection/RedisClientEntry.java, src/main/java/org/redisson/core/NodesGroup.java
What about hiding connection exception as ping failure?
=> Failing ping request in case when server is unreachable instead of exception

src/test/java/org/redisson/RedisRunner.java, src/test/java/org/redisson/RedissonMultiLockTest.java, src/test/java/org/redisson/RedissonTest.java, src/test/resources/redis_connectionListener_test.conf, src/test/resources/redis_multiLock_test_instance1.conf, src/test/resources/redis_multiLock_test_instance2.conf, src/test/resources/redis_multiLock_test_instance3.conf, src/test/resources/redis_oom_test.conf
Reverts mrniko/redisson#439. Sorry! But @jackygurui have already refactored this thing in bit another way.
=> Revert "Untie tests from Windows absolute paths"

README.md
=> Bump up version number in README.md

src/main/java/org/redisson/client/protocol/decoder/KeyValueObjectDecoder.java, src/test/java/org/redisson/RedissonBlockingQueueTest.java
The ArrayOutOfBoundsException is thrown and returned null when polling from a RedissonBlockingQueue with key size is exactly 1.
=> Fix issue #487

src/main/java/org/redisson/RedissonRemoteService.java, src/test/java/org/redisson/RedissonRemoteServiceTest.java
fix #496
This PR is atop of my [executors-amount-is-not-enforced](https://github.com/pierredavidbelanger/redisson/tree/executors-amount-is-not-enforced) branch, so it contains the test case along with its fix.
Just dont merge this PR blindly as the code fail miserably the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) ;)
I guess it pin point where the problem is, and I just hope it will inspire you to find a more elegant solution.
=> Executors amount is not enforced (failing test case AND its fix)

src/main/java/org/redisson/connection/ClientConnectionsEntry.java, src/main/java/org/redisson/connection/pool/ConnectionPool.java
https://github.com/mrniko/redisson/issues/518
=> improve auth reconnect

src/main/java/org/redisson/RedissonListMultimap.java, src/main/java/org/redisson/RedissonMultimap.java, src/main/java/org/redisson/RedissonSetMultimap.java, src/main/java/org/redisson/core/RMultimap.java, src/main/java/org/redisson/core/RMultimapAsync.java, src/test/java/org/redisson/RedissonListMultimapTest.java, src/test/java/org/redisson/RedissonSetMultimapTest.java
Adding a new functionality which gets the count of all the distinct keys for a multimap.
=> Adding keySize functionality for MultiMaps

src/main/java/org/redisson/client/handler/CommandDecoder.java
Based on doc for method public abstract ByteBuf readBytes(int length) in io.netty.buffer.ByteBuf, the method returns a newly created buffer which contains the transferred bytes, which means we have to manually release this buffer.
=> To fix memory leak #535

CONTRIBUTING.md
It was a little tricky to find how to run all the tests in the build. This is what I could tease out of your travis build.
Please let me know if this is good enough and if it's the appropriate place for it.
=> Documenting local build

src/main/java/org/redisson/Redisson.java, src/main/java/org/redisson/RedissonReactive.java
Redisson and RedissonReactive can be extends.
=> 	Redisson and RedissonReactive can be extends.

redisson/src/main/java/org/redisson/connection/balancer/WeightedRoundRobinBalancer.java, redisson/src/test/java/org/redisson/connection/balancer/WeightedRoundRobinBalancerTest.java
@mrniko This changes fixes #582 and may be the desired behaviour.
=> #582: Always find a connection to read

redisson/src/main/java/org/redisson/misc/RedissonObjectFactory.java
Fixed RLiveObject in RedissonReference
=> Redisson reference

redisson/src/test/java/org/redisson/executor/RedissonExecutorServiceTest.java, redisson/src/test/java/org/redisson/executor/RedissonScheduledExecutorServiceTest.java
Fixed testing with travisEnv flag turned off
=> Test timeout

redisson/src/main/java/org/redisson/Redisson.java, redisson/src/main/java/org/redisson/RedissonExecutorService.java, redisson/src/main/java/org/redisson/api/RedissonClient.java, redisson/src/test/java/org/redisson/RedissonRemoteServiceTest.java
Hi there!
Just found a type by accident. Hope it would be helpful to merge!
=> Fixed type getRemoteSerivce -> getRemoteService

redisson/src/main/java/org/redisson/client/RedisClient.java
Fixes https://github.com/redisson/redisson/issues/671.
=> Add null check for timer and assign to variable so it is shutdown..

redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java, redisson/src/main/java/org/redisson/client/protocol/CommandData.java, redisson/src/main/java/org/redisson/command/CommandAsyncService.java, redisson/src/main/java/org/redisson/misc/LogHelper.java, redisson/src/test/java/org/redisson/misc/LogHelperTest.java
=> Introduce LogHelper to prevent excessive byte[] logging

redisson/src/main/java/org/redisson/BaseRemoteService.java, redisson/src/main/java/org/redisson/RedissonRemoteService.java, redisson/src/main/java/org/redisson/remote/RemoteServiceKey.java, redisson/src/main/java/org/redisson/remote/RemoteServiceRequest.java, redisson/src/test/java/org/redisson/RedissonRemoteServiceTest.java
RedissonRemoveService now supports method overload
=> Remote service method override for #760

redisson/src/main/java/org/redisson/config/Config.java, redisson/src/main/java/org/redisson/config/ConfigSupport.java
Pull request for #802 on master branch
=> Adding support to supply custom connection manager

redisson/pom.xml
see https://github.com/redisson/redisson/issues/793
=> Make spring-boot-actuator bundle as optional

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/RMapCache.java, redisson/src/main/java/org/redisson/api/RMapCacheAsync.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
Hello~
I added RMapCache.fastPutIfAbsent with ttl (RmapCacheAsync.fastPutIfAbsentAsync too).
=> fix the #699

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
fixed #827 by extending addAndGet method and made it packed content aware
=> fix the #827

redisson/src/main/resources/org/redisson/spring/support/redisson-1.0.xsd, redisson/src/test/java/org/redisson/spring/support/SpringNamespaceWikiTest.java, redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_single_with_placeholder.xml
added  a test case to cover the change
=> Changing data types in xsd file to strings. Fix #848

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
Fix incorrect use of local cache in resolution of RedissonLocalCachedMap getAllAsync
=> Fixed local cache resolution of getAllAsync

redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java, redisson/src/main/java/org/redisson/api/RLocalCachedMap.java
Added method to RLocalCachedMap to allow cache-preloading
=> Added pre-warm mechanism for locally cached maps

redisson/src/main/java/org/redisson/RedissonKeys.java
=> Using Scan command in deleteByPattern

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
Modify the param of RedissonSessionRepository's method publishEvent from Object to ApplicationEvent to compatible with  all spring version
=> [Spring-Session Compatible]

redisson/src/main/java/org/redisson/client/codec/ByteArrayCodec.java, redisson/src/main/java/org/redisson/client/codec/JsonJacksonMapCodec.java, redisson/src/main/java/org/redisson/client/codec/StringCodec.java, redisson/src/main/java/org/redisson/client/protocol/DefaultParamsEncoder.java, redisson/src/main/java/org/redisson/codec/FstCodec.java, redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java, redisson/src/main/java/org/redisson/codec/KryoCodec.java, redisson/src/main/java/org/redisson/codec/LZ4Codec.java, redisson/src/main/java/org/redisson/codec/SerializationCodec.java, redisson/src/main/java/org/redisson/codec/SnappyCodec.java, redisson/src/main/java/org/redisson/command/CommandAsyncService.java, redisson/src/main/java/org/redisson/executor/TasksRunnerService.java, redisson/src/main/java/org/redisson/misc/Hash.java
Performance boost for utf8 string encoding.
=> Ensure bytebufs are released if various encoders throw exception.

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/MapOptions.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
=> Revert "Add support for bounded Redisson map cache (max size configuration). "

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/client/codec/StringCodec.java
Fixes regressions introduced by https://github.com/redisson/redisson/commit/4a25fab9df7ee9ef84416609c445ff9b12b3238a
=> Revert changes to StringCodec and fix script compilation.

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
We need the way to add or override item and get rank right away
```
Integer addAndGetRank(double score, V object);
RFuture<Integer> addAndGetRankAsync(double score, V object);
Integer addAndGetRevRan(double score, V object);
RFuture<Integer> addAndGetRevRankAsync(double score, V object);
```
=> Add methods to add item and get rank for RedissonScoredSortedSet

redisson/src/main/java/org/redisson/config/Config.java, redisson/src/main/java/org/redisson/connection/AddressResolverGroupFactory.java, redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java
=> add ability to use RoundRobinDnsAddressResolverGroup in Connection manager. 

README.md
Fix links for Integration with frameworks wiki page
=> Fix links for Integration with frameworks wiki page

redisson/src/main/java/org/redisson/api/RedissonClient.java
=> fix javadoc

redisson/src/main/resources/META-INF/spring.schemas
=> add redisson-1.2.xsd to spring.schemas

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/RMapCache.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
This adds the methods putAll and putAllAsync with ttl and ttlUnit to RMapCache and RedissonMapCache.
This is not a common use case of a cache, but we need it in our project anyway.
=> add putAll with ttl

redisson-tomcat/redisson-tomcat-6/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/UpdateValve.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/UpdateValve.java
UpdateValve could invoke manager.store() multiple times per request processing, for example if the request processing involves includes and/or forward of the request to another servlet/jsp to complete request processing. Change UpdateValve to only invoke storage of attributes into Redis only once per request
=> UpdateValve needs to execute manager.store only once at the end of the request #2084

redisson/src/main/java/org/redisson/config/SentinelServersConfig.java, redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
I have the same issue that was in cluster, but in sentinel configuration.
Hope it helps
Thanks!
=> Add natMap for Sentinel configuration

redisson/src/main/java/org/redisson/codec/SerializationCodec.java, redisson/src/main/java/org/redisson/executor/TasksRunnerService.java
ClassNotFoundException occur during object deserialization in SerializationCodec
=> resolves issue: ClassNotFoundException thrown during SeriazliationCodec.decode #2136

pom.xml, redisson-all/pom.xml, redisson/pom.xml
add default entries in MANIFEST.MF file and extra Build-Time entry as well #2185
=> add default entries in MANIFEST.MF file and extra Build-Time entry as well #2185

redisson/src/main/java/org/redisson/api/RSetReactive.java, redisson/src/main/java/org/redisson/api/RSetRx.java, redisson/src/test/java/org/redisson/RedissonSetReactiveTest.java, redisson/src/test/java/org/redisson/rx/RedissonSetRxTest.java
=> Set.intersection should return a Single, or Mono, of Integer

redisson/src/main/java/org/redisson/api/RSetReactive.java, redisson/src/main/java/org/redisson/api/RSetRx.java, redisson/src/test/java/org/redisson/RedissonSetReactiveTest.java, redisson/src/test/java/org/redisson/rx/RedissonSetRxTest.java
Reverts redisson/redisson#2242
=> Revert "Set.intersection should return a Single, or Mono, of Integer"

redisson/src/main/java/org/redisson/client/protocol/decoder/ClusterNodesDecoder.java
=> ClusterNodesDecoder ignore unknown flag and avoid throwing exception, fix bug #2399

README.md
@mrniko do I need to update some script processors / release scripts?
=> Add sbt dependency to readme

redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java
During #2539, while one problem was certainly that the connections of removed sentinels were not properly closed, we noticed that the primary problem is that the DNS check is constantly adding our load balancer IP to the sentinels map. In order to circumvent this, we disabled the DNS check by setting the monitoring interval to -1, but then we lost the ability to reconnect to the cluster in case all connections failed.
So in order to preserve the ability to reconnect to the cluster while still avoiding to constantly create new connections due to the DNS check, we introduced a configuration setting that allows to only perform the DNS check in case all connections have failed. We thought about adding this behavior as part of the -1 monitoring interval configuration, but decided that it is …
=> Perform Sentinel DNS check when all connections fail

redisson/src/main/java/org/redisson/codec/FstCodec.java
=> Use FSTConfiguration#deriveConfiguration to preserve ConfType

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
=> Use the session map’s codec when getting the map

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
This is a potential fix for #2690.
=> Fixed - RedissonSessionRepository topic listener NPE race

redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
=> RedissonSession#changeSessionId - PTTL and stale map fixes

redisson/src/main/java/org/redisson/client/protocol/decoder/StreamInfoDecoder.java
Adds functionality for decoding StreamInfo with changing order of fields in response of XINFO.
It's a possible solution for #2818 and should also work if number or order of fields in XINFO response changes in the future.
=> Fixed StreamInfoDecoder to adapt to layout of XINFO response. Possible solution for #2818

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java, redisson/src/test/java/org/redisson/RedissonSetTest.java
fixes [https://github.com/redisson/redisson/issues/2896](https://github.com/redisson/redisson/issues/2896)
=> Fix ClusterConnectionManager#calcSlot bug.

CHANGELOG.md, redisson/src/main/java/org/redisson/RedissonRx.java, redisson/src/main/java/org/redisson/RedissonSetMultimapCache.java, redisson/src/main/java/org/redisson/api/RBatchRx.java, redisson/src/main/java/org/redisson/api/RListMultimapCacheRx.java, redisson/src/main/java/org/redisson/api/RMultimapCacheRx.java, redisson/src/main/java/org/redisson/api/RSetMultimapCacheRx.java, redisson/src/main/java/org/redisson/api/RedissonRxClient.java, redisson/src/main/java/org/redisson/rx/RedissonBatchRx.java, redisson/src/main/java/org/redisson/rx/RedissonListMultimapCacheRx.java, redisson/src/main/java/org/redisson/rx/RedissonListMultimapRx.java, redisson/src/main/java/org/redisson/rx/RedissonSetMultimapCacheRx.java, redisson/src/main/java/org/redisson/rx/RedissonSetMultimapRx.java
Hi @mrniko , I have added this PR to implement the feature request I reported in #3139. I tried my best to adhere to the existing code style. If you have the time to take a look at it, that would be great. Thank you.
Kind regards,
Marnix Kammer
=> Implemented feature request #3139: Added cache multimap variants for the Rx API

redisson/src/main/java/org/redisson/RedissonLock.java
修改redisson断线重连后无法再续期的问题
Fix watchdog won't renew after reconnect
issue #3194
Signed-off-by: 王彬 <burgleaf@gmail.com>
=> Fix watchdog won't renew after reconnect

redisson/src/main/java/org/redisson/RedisNodes.java
- if some node ping result not true, just break foreach!
=> RedisNodes ping results check optimization

redisson/src/main/java/org/redisson/client/handler/ConnectionWatchdog.java
fix:
1) reconnect success,but old redisConnection is closed, need close new redisConnection(and channel),otherwish,this connection not in allconnections and freeconnections,it‘s leaked
2) when reconnect success, refresh channel to oldconnection, but not check old redisConnection isclosed
Issue:https://github.com/redisson/redisson/issues/3270
=> fix: ConnectionWatchdog connection leak;

redisson/src/main/java/org/redisson/connection/ClientConnectionsEntry.java, redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java
add initing status in entry, and set entry freezed status null when all connection inited
issue: https://github.com/redisson/redisson/issues/3270
Signed-off-by: xujie <mikawudi@qq.com>
=> fix: connection leak when initConnections

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
=> Set connection to fail when all slaves init connections error

redisson/src/main/java/org/redisson/Redisson.java, redisson/src/main/java/org/redisson/RedissonBaseLock.java, redisson/src/main/java/org/redisson/RedissonLock.java, redisson/src/main/java/org/redisson/RedissonReactive.java, redisson/src/main/java/org/redisson/RedissonRx.java, redisson/src/main/java/org/redisson/RedissonSpinLock.java, redisson/src/main/java/org/redisson/api/LockOptions.java, redisson/src/main/java/org/redisson/api/RedissonClient.java, redisson/src/main/java/org/redisson/api/RedissonReactiveClient.java, redisson/src/main/java/org/redisson/api/RedissonRxClient.java, redisson/src/test/java/org/redisson/LockOptionsTest.java, redisson/src/test/java/org/redisson/RedissonSpinLockBackoffTest.java, redisson/src/test/java/org/redisson/RedissonSpinLockTest.java
Implemented spin locks and 2 back off algorithms. 
Docs will be added after global implementation ideas are approved.
#3349
=> Implemented spin locks

redisson/src/main/java/org/redisson/RedissonFairLock.java, redisson/src/main/java/org/redisson/RedissonLock.java, redisson/src/main/java/org/redisson/RedissonReadLock.java, redisson/src/main/java/org/redisson/RedissonWriteLock.java
issue #3484 
Signed-off-by: 小乌龟不会写代码 <41791762+coding-tortoise@users.noreply.github.com>
=> fixed There may be concurrency problems in org.redisson.RedissonLock#tryLockInnerAsync issue #3484

redisson/src/main/java/org/redisson/jcache/JCacheEventCodec.java
=> fix: release ByteBuf causing leak

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
fix https://github.com/redisson/redisson/issues/3635
=> fix ClusterConnectionManager#checkSlotsMigration map slot-partitions bug after re-sharding slots

redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
fix https://github.com/redisson/redisson/issues/3695
=> ClusterPartition#slotRanges not update in ClusterConnectionManager#checkSlotsMigration 

pom.xml
=> update Netty to 4.1.66.Final

redisson/src/main/java/org/redisson/RedissonBuckets.java, redisson/src/main/java/org/redisson/command/CommandAsyncExecutor.java, redisson/src/main/java/org/redisson/command/CommandAsyncService.java
bug import in this issue
https://github.com/redisson/redisson/issues/3810
and in this commit
https://github.com/redisson/redisson/commit/c875cc3003637d97785ab05a2d9fe46408ea57c0
=> fix: fix bug for mset cross slot (miss values except cluster mode)

redisson/src/main/java/org/redisson/RedissonBaseLock.java, redisson/src/main/java/org/redisson/command/CommandAsyncService.java, redisson/src/test/java/org/redisson/RedissonLockTest.java
Fixes https://github.com/redisson/redisson/issues/2714
=> Fix "TryLock interrupted keeps renewing lock indefinitely"

redisson/src/main/java/org/redisson/RedissonBuckets.java, redisson/src/main/java/org/redisson/connection/DNSMonitor.java
bug import in this issue
https://github.com/redisson/redisson/issues/3929
and in this commit
https://github.com/redisson/redisson/commit/796645f655e348fc782d68ce89fd69841fc92ca7
=> fix: fix bug for msetnx cross slot in Redis cluster mode

.gitignore
Signed-off-by: lan <1728209643@qq.com>
=> Remove duplicate items in `.gitignore`

redisson/src/main/java/org/redisson/RedissonExecutorService.java
fix for https://github.com/redisson/redisson/issues/4384
=> fix ClassCastException when submiting an async task with ttl - 4384

redisson-spring-data/redisson-spring-data-20/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-21/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-24/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-25/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-26/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java, redisson-spring-data/redisson-spring-data-27/src/main/java/org/redisson/spring/data/connection/RedissonReactiveStringCommands.java
if setIfAbsent is fail,return default value "false"
Signed-off-by: 庄子斌 <zhuangzibin@leyaoyao.com>
=> fix: setIfAbsent empty

redisson/src/main/java/org/redisson/RedissonSortedSet.java
fix #4594
Signed-off-by: yuwei <yuwei@wesine.com>
=> fix add() method throw NPE 

redisson/src/main/java/org/redisson/RedissonRateLimiter.java
Set a default value for RateLimiterConfig
=> RateLimiterConfig should have  default values

redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java
Fixes https://github.com/redisson/redisson/issues/4678 via the analogous change to https://github.com/redisson/redisson/commit/011be4160aeb5e23510e6715c16531ccaea07db9 in RedissonSemaphore
=> Fix bug in trySetPermitsAsync of RedissonPermitExpirableSemaphore

redisson/src/main/java/org/redisson/client/handler/CommandPubSubDecoder.java, redisson/src/test/java/org/redisson/client/handler/CommandPubSubDecoderTest.java
SharedPubSub listener not being triggered, because missed processing `smessage` command
=> Fixed - SharedPubSub listener not being triggered

redisson-tomcat/README.md
Trying to improve the grammar in the Tomcat README.
=> Fix grammar and typo in Tomcat README

redisson/src/main/java/org/redisson/RedissonSpinLock.java, redisson/src/test/java/org/redisson/RedissonSpinLockTest.java
This PR fixes  #5002. Please note new test `testTryLockAsyncWaitTime` - it fails with old implementation and clearly illustrates issue with `tryLockAsync`. For synchronous  `tryLock` issue is less noticeable, but I fixed it in order to be consistent with `tryLockAsync`.
=> Fixed wait time handling in RedissonSpinLock #5002

redisson/src/main/java/org/redisson/RedissonRateLimiter.java, redisson/src/test/java/org/redisson/RedissonRateLimiterTest.java
RRateLimiter#setRate does not behave as expected when RateType is pre_client
=> Fixed: issue #5098 - RRateLimiter#setRate does not behave as expected

redisson-spring-boot-starter/README.md
=> Fix "Redis settings in redisson-spring-boot-starter README is deprecated."(#5138)

redisson/src/main/java/org/redisson/api/search/aggregate/ReducerParams.java
Ft.AGGREGATE fails when using reducer with alias name
=> Reducer as alias fix

redisson/src/main/java/org/redisson/RedissonRemoteService.java
Reverts redisson/redisson#5442
=> Revert "Revert "Log swallowed exception in RedissonRemoteService sending request ack""

redisson/src/main/java/org/redisson/connection/DnsAddressResolverGroupFactory.java
https://github.com/redisson/redisson/issues/5572
=> Enable DNS TCP fallback when UDP query timeout

redisson-spring-data/redisson-spring-data-26/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-27/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-30/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-31/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java, redisson-spring-data/redisson-spring-data-32/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java
Signed-off-by: chenxiabin <czchenxiabin@gmail.com> #5678
=> fix ZPOPMIN\ZPOPMAX to count members error

redisson/src/main/java/org/redisson/command/CommandAsyncService.java, redisson/src/test/java/org/redisson/RedissonBatchTest.java
Fix issue #5693 - RBatch does not work with randomKeyAsync
=> Fix issue #5693 - RBatch does not work with randomKeyAsync

redisson/src/main/java/org/redisson/RedissonPatternTopic.java, redisson/src/main/java/org/redisson/api/RPatternTopic.java, redisson/src/main/java/org/redisson/api/RPatternTopicReactive.java, redisson/src/main/java/org/redisson/api/RPatternTopicRx.java
Use PUBSUB CHANNELS PATTERN command to lists the currently active channels of the corresponding pattern topic
=> Add getActiveTopic method

redisson/src/main/java/org/redisson/command/CommandBatchService.java, redisson/src/test/java/org/redisson/RedissonBatchTest.java
more information
https://github.com/redisson/redisson/issues/5707
=> Fixed - append commands error when using batch mode

redisson/pom.xml, redisson/src/test/java/org/redisson/codec/protobuf/nativeData/Proto2AllTypes.java, redisson/src/test/java/org/redisson/codec/protobuf/nativeData/Proto3AllTypes.java
Upgraded according to the instructions of the following issue
https://github.com/protocolbuffers/protobuf/issues/16452
=> upgrade protobuf from 3.16.3 to 4.27.2

redisson/src/main/java/org/redisson/RedissonSearch.java, redisson/src/main/java/org/redisson/api/search/aggregate/AggregationOptions.java, redisson/src/main/java/org/redisson/api/search/query/QueryOptions.java
=> Allow to specify WITHCOUNT in QueryOptions / AggregationOptions 

redisson/src/main/java/org/redisson/RedissonSetCache.java, redisson/src/main/java/org/redisson/api/RSetCache.java, redisson/src/main/java/org/redisson/api/RSetCacheAsync.java, redisson/src/main/java/org/redisson/api/RSetCacheReactive.java, redisson/src/main/java/org/redisson/api/RSetCacheRx.java, redisson/src/test/java/org/redisson/RedissonSetCacheReactiveTest.java, redisson/src/test/java/org/redisson/RedissonSetCacheTest.java, redisson/src/test/java/org/redisson/rx/RedissonSetCacheRxTest.java
Added RSetCache.addIfAbsent(Map<V, Duration> objects) method
=> Feature -  RSetCache.addIfAbsent(Map<V, Duration> objects)  added

redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/RMapCache.java, redisson/src/main/java/org/redisson/api/RMapCacheReactive.java, redisson/src/main/java/org/redisson/api/RMapCacheRx.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
Feature - add computeIfAbsent with TTL method to RMapCache #6136
Sorry i accidentally closed the PR.
=> Feature - add computeIfAbsent with TTL method to RMapCache #6136

redisson-tomcat/README.md, redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java, redisson-tomcat/redisson-tomcat-9/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java, redisson-tomcat/redisson-tomcat-9/src/test/java/org/redisson/tomcat/TomcatServer.java, redisson-tomcat/redisson-tomcat-9/src/test/webapp/META-INF/context_empty.xml
see feature request: https://github.com/redisson/redisson/issues/6178
If this is the right way, the changes should be copied also to tomcat10 and probably tomcat8. Official support in spring boot is for Tomcat 8.5 and above
=> Tomcat Session Manager - allow to use programmatically configured config object

redisson/src/main/java/org/redisson/RedissonRateLimiter.java
Add check, The parameter timeToLive should be greater than or equal to rateInterval
=>  Add check code for RRateLimiter.trySetRate

redisson/src/main/java/org/redisson/Redisson.java, redisson/src/main/java/org/redisson/RedissonFasterMultiLock.java, redisson/src/main/java/org/redisson/RedissonReactive.java, redisson/src/main/java/org/redisson/RedissonRx.java, redisson/src/main/java/org/redisson/api/RedissonClient.java, redisson/src/main/java/org/redisson/api/RedissonReactiveClient.java, redisson/src/main/java/org/redisson/api/RedissonRxClient.java, redisson/src/test/java/org/redisson/RedissonFasterMultiLockTest.java
I copied codes from RedissonLock and rewrite some core methods, The same as test unit.
=> Feature - Add RedissonFasterMultiLock

redisson-spring-data/redisson-spring-data-33/src/main/java/org/redisson/spring/data/connection/RedissonClusterConnection.java, redisson-spring-data/redisson-spring-data-33/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java
- Spring Data 3.3 deprecated `long cursorId` in favor of String-backed `CursorId` object to avoid `NumberFormatException` when then cursor ID is bigger than max long
- more info: https://github.com/spring-projects/spring-data-redis/issues/2796
=> use CursorId in ScanIteration to avoid long overflow

redisson/src/main/java/org/redisson/RedissonAtomicDouble.java, redisson/src/main/java/org/redisson/RedissonAtomicLong.java, redisson/src/main/java/org/redisson/api/RAtomicDouble.java, redisson/src/main/java/org/redisson/api/RAtomicDoubleAsync.java, redisson/src/main/java/org/redisson/api/RAtomicDoubleReactive.java, redisson/src/main/java/org/redisson/api/RAtomicDoubleRx.java, redisson/src/main/java/org/redisson/api/RAtomicLong.java, redisson/src/main/java/org/redisson/api/RAtomicLongAsync.java, redisson/src/main/java/org/redisson/api/RAtomicLongReactive.java, redisson/src/main/java/org/redisson/api/RAtomicLongRx.java, redisson/src/test/java/org/redisson/RedissonAtomicDoubleTest.java, redisson/src/test/java/org/redisson/RedissonAtomicLongReactiveTest.java, redisson/src/test/java/org/redisson/RedissonAtomicLongTest.java
I also have similar scenarios that need to be supported by relevant methods.
more information.
[4455](https://github.com/redisson/redisson/issues/4455)。
=> Feature - Atomic class add greaterThanSet and lessThanSet method

redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphore.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreAsync.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreReactive.java, redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreRx.java, redisson/src/test/java/org/redisson/RedissonPermitExpirableSemaphoreTest.java
[issues/5448](https://github.com/redisson/redisson/issues/5448)
=> Feature - getLeaseTime() for RPermitExpirableSemaphore

redisson/src/main/java/org/redisson/executor/TasksRunnerService.java, redisson/src/test/java/org/redisson/executor/RedissonExecutorServiceTest.java
[issues/#5577](https://github.com/redisson/redisson/issues/5577)
=> Fixed - Task not firing on the next executor if app was killed #5577

redisson/src/main/java/org/redisson/remote/BaseRemoteProxy.java, redisson/src/test/java/org/redisson/RedissonRemoteServiceTest.java
[issue#6361](https://github.com/redisson/redisson/issues/6361)
=> Fixed - responseFuture not finished

redisson/src/main/java/org/redisson/spring/cache/CacheConfig.java, redisson/src/main/java/org/redisson/spring/cache/CacheConfigSupport.java, redisson/src/main/java/org/redisson/spring/cache/RedissonSpringCacheManager.java, redisson/src/test/java/org/redisson/spring/cache/RedissonSpringCacheShortTTLTest.java, redisson/src/test/resources/org/redisson/spring/cache/cache-config-shortTTL.json
Related: [#5646](https://github.com/redisson/redisson/issues/5646)
=> Feat spring cache listener

redisson-spring-data/redisson-spring-data-16/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java
One file is missing code formatting
=> Style - code format

redisson/src/main/java/org/redisson/executor/ScheduledTasksService.java, redisson/src/main/java/org/redisson/executor/TasksRunnerService.java
[issue#5368](https://github.com/redisson/redisson/issues/5368)
=> Fixed - cancel schedule task occurs concurrency problem

redisson/src/main/java/org/redisson/RedissonMultiLock.java, redisson/src/main/java/org/redisson/api/RLock.java, redisson/src/main/java/org/redisson/api/RLockAsync.java, redisson/src/main/java/org/redisson/api/RLockReactive.java, redisson/src/main/java/org/redisson/api/RLockRx.java, redisson/src/main/java/org/redisson/api/RObservable.java, redisson/src/main/java/org/redisson/api/RObservableAsync.java, redisson/src/main/java/org/redisson/api/RObservableReactive.java, redisson/src/main/java/org/redisson/api/RObservableRx.java, redisson/src/test/java/org/redisson/RedissonLockReactiveTest.java, redisson/src/test/java/org/redisson/RedissonLockRxTest.java, redisson/src/test/java/org/redisson/RedissonLockTest.java
[issues/3854](https://github.com/redisson/redisson/issues/3854)
=> Feature - RObservable for Lock object listener #3854

redisson/src/main/java/org/redisson/RedissonRemoteService.java, redisson/src/test/java/org/redisson/executor/RedissonExecutorServiceTest.java
[issues/6387](https://github.com/redisson/redisson/issues/6387)
=> Fixed - worker stop working #6387

redisson/src/main/java/org/redisson/client/protocol/decoder/SearchResultDecoder.java, redisson/src/test/java/org/redisson/RedissonSearchTest.java
[issues/6405](https://github.com/redisson/redisson/issues/6405)
=> Fixed - search error with nocontent param

redisson/src/main/java/org/redisson/RedissonKeys.java, redisson/src/main/java/org/redisson/api/RKeysAsync.java, redisson/src/main/java/org/redisson/iterator/BaseAsyncIterator.java, redisson/src/main/java/org/redisson/misc/CompositeAsyncIterator.java, redisson/src/test/java/org/redisson/RedissonKeysTest.java
[issues/#6377](https://github.com/redisson/redisson/issues/6377)
=> Feature - RKeyAsync getKeysAsync

redisson/src/main/java/org/redisson/spring/cache/CacheConfig.java, redisson/src/main/java/org/redisson/spring/cache/RedissonSpringCacheManager.java
Improvements were added to the flexible cache settings for eviction mode.
=> Add ability to set eviction mode for Cache Config

redisson/src/main/java/org/redisson/RedissonBitSet.java, redisson/src/main/java/org/redisson/api/RBitSet.java, redisson/src/main/java/org/redisson/api/RBitSetAsync.java, redisson/src/main/java/org/redisson/api/RBitSetReactive.java, redisson/src/main/java/org/redisson/api/RBitSetRx.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/main/java/org/redisson/client/protocol/decoder/ArrayBooleanDecoder.java, redisson/src/test/java/org/redisson/RedissonBitSetReactiveTest.java, redisson/src/test/java/org/redisson/RedissonBitSetTest.java
[issues/5216](https://github.com/redisson/redisson/issues/5216)
=> Feature - Bitset add method get(Long ...x1)

redisson/pom.xml, redisson/src/test/java/org/redisson/codec/protobuf/nativeData/Proto2AllTypes.java, redisson/src/test/java/org/redisson/codec/protobuf/nativeData/Proto3AllTypes.java
replace @Deprecated class for protobuf upgrade plan
=> upgrade protobuf from 4.27.2 to 4.29.3

redisson/src/main/java/org/redisson/RedissonBlockingDeque.java, redisson/src/main/java/org/redisson/RedissonBlockingQueue.java, redisson/src/main/java/org/redisson/RedissonBoundedBlockingQueue.java, redisson/src/main/java/org/redisson/RedissonPriorityBlockingDeque.java, redisson/src/main/java/org/redisson/RedissonPriorityBlockingQueue.java, redisson/src/main/java/org/redisson/RedissonTransferQueue.java, redisson/src/main/java/org/redisson/api/RBlockingQueue.java, redisson/src/main/java/org/redisson/api/RBlockingQueueAsync.java, redisson/src/main/java/org/redisson/api/RBlockingQueueReactive.java, redisson/src/main/java/org/redisson/api/RBlockingQueueRx.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonBlockingQueueTest.java
[issues/2773](https://github.com/redisson/redisson/issues/2773)
=> Feature poll last with name

redisson/src/main/java/org/redisson/RedissonObject.java, redisson/src/main/java/org/redisson/api/ObjectEncoding.java, redisson/src/main/java/org/redisson/api/RObject.java, redisson/src/main/java/org/redisson/api/RObjectAsync.java, redisson/src/main/java/org/redisson/api/RObjectReactive.java, redisson/src/main/java/org/redisson/api/RObjectRx.java, redisson/src/main/java/org/redisson/api/RedisObjectEncoding.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedisDockerTest.java, redisson/src/test/java/org/redisson/RedissonBucketTest.java
[issues/2849](https://github.com/redisson/redisson/issues/2849)
=> Feature - Support for OBJECT command

redisson/src/main/java/org/redisson/RedissonFairLock.java
[issues/5989](https://github.com/redisson/redisson/issues/5989)
=> Fixed - Fair Lock attempt to compare nil with number

redisson/src/main/java/org/redisson/RedissonSearch.java, redisson/src/test/java/org/redisson/RedissonSearchTest.java
[issues/5966](https://github.com/redisson/redisson/issues/5966)
=> Improvement - validate PARAMS in search method

redisson/src/main/java/org/redisson/RedissonMap.java, redisson/src/main/java/org/redisson/api/RMapAsync.java, redisson/src/test/java/org/redisson/RedissonMapTest.java
[issues/5918](https://github.com/redisson/redisson/issues/5918)
=> Feature - Obtain values from RMap, based on key pattern, asynchronously

redisson-micronaut/redisson-micronaut-20/src/main/java/org/redisson/micronaut/cache/RedissonAsyncCache.java, redisson-micronaut/redisson-micronaut-20/src/test/java/org/redisson/micronaut/RedissonCacheTest.java, redisson-micronaut/redisson-micronaut-30/src/main/java/org/redisson/micronaut/cache/RedissonAsyncCache.java, redisson-micronaut/redisson-micronaut-30/src/test/java/org/redisson/micronaut/RedissonCacheTest.java, redisson-micronaut/redisson-micronaut-40/src/main/java/org/redisson/micronaut/cache/RedissonAsyncCache.java, redisson-micronaut/redisson-micronaut-40/src/test/java/org/redisson/micronaut/RedissonCacheTest.java
[issues/6414](https://github.com/redisson/redisson/issues/6414)
=> Fixed - Issue with asynchronous @Cacheable methods

redisson/src/main/java/org/redisson/connection/ClusterConnectionManager.java
[issues/6339](https://github.com/redisson/redisson/issues/6339)
=> Fixed - Adding a new slave node in redis-cluster, isSlaveNotUsed does not take effect

redisson/src/main/java/org/redisson/QueueTransferTask.java
[issues/6371](https://github.com/redisson/redisson/issues/6371)
=> Fixed - RDelayedQueue cannot get anything when server run a long time

redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java
[issues/6223](https://github.com/redisson/redisson/issues/6223)
=> Fixed - a new attempt should be made on WAIT error during failover

redisson/src/main/java/org/redisson/renewal/LockEntry.java, redisson/src/test/java/org/redisson/RedissonLockExpirationRenewalTest.java
[issues/6144](https://github.com/redisson/redisson/issues/6144)
=> Fixed - Watchdog fails to renew on reentry locks

redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java
[issues/6026](https://github.com/redisson/redisson/issues/6026)
=> Fixed - PubSub stops working after Redis restart in sentinel mode #6026

redisson/src/main/java/org/redisson/jcache/JCacheManager.java, redisson/src/test/java/org/redisson/jcache/JCacheTest.java
[issues/6575](https://github.com/redisson/redisson/issues/6575)
=> Fixed - JCacheManager does not remove cache instance from map when calling closeCache() #6575

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
=> Feature - SocreSortedSet diff/union/intersect: add readDiffEntries() method

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/main/java/org/redisson/api/SetIntersectionArgs.java, redisson/src/main/java/org/redisson/api/SetIntersectionParams.java, redisson/src/main/java/org/redisson/api/SetReadArgs.java, redisson/src/main/java/org/redisson/api/SetReadArgsParam.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
=> Feature - SocreSortedSet diff/union/intersect:add readIntersection() method #6562

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
=> Feature - SocreSortedSet diff/union/intersect:add readIntersectionEntries() method #6562

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/main/java/org/redisson/api/SetIntersectionArgs.java, redisson/src/main/java/org/redisson/api/SetReadArgs.java, redisson/src/main/java/org/redisson/api/SetUnionArgs.java, redisson/src/main/java/org/redisson/api/SetUnionParams.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
=> Feature - SocreSortedSet diff/union/intersect:add readUnion() method #6562

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
=> Feature - SocreSortedSet diff/union/intersect:add readUnionEntries() method #6562

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/test/java/org/redisson/RedissonScoredSortedSetTest.java
[issues/6602](https://github.com/redisson/redisson/issues/6602)
=> Feature - Refactor union() and intersection() methods of RScoredSortedSet #6602

redisson/src/main/java/org/redisson/RedissonMap.java, redisson/src/test/java/org/redisson/RedissonMapTest.java
[issues/6566](https://github.com/redisson/redisson/issues/6566)
=> Fixed - The count parameter should not limit the number of results returned

redisson/src/main/java/org/redisson/RedissonSet.java, redisson/src/main/java/org/redisson/RedissonSetCache.java, redisson/src/main/java/org/redisson/RedissonSetMultimapValues.java, redisson/src/main/java/org/redisson/api/RSetAsync.java, redisson/src/test/java/org/redisson/RedissonSetCacheTest.java, redisson/src/test/java/org/redisson/RedissonSetMultimapCacheTest.java, redisson/src/test/java/org/redisson/RedissonSetTest.java
[issues/6570](https://github.com/redisson/redisson/issues/6570)
=> Feature - Add Support for Asynchronous Batch Iteration in RSet Interface #6570

redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
[issues/6586](https://github.com/redisson/redisson/issues/6586)
=> Feature - MapCache nameMapper test add #6586

redisson/src/main/java/org/redisson/cache/LFUCacheMap.java
=> Fixed add lock for LFU.onMapFull #6663

redisson/src/main/java/org/redisson/connection/ServiceManager.java, redisson/src/test/java/org/redisson/RedissonTest.java
[issues/6668](https://github.com/redisson/redisson/issues/6668)
=> Fixed - DNSMonitor logs a warning #6668

redisson/src/main/java/org/redisson/RedissonStream.java, redisson/src/main/java/org/redisson/api/RStream.java, redisson/src/main/java/org/redisson/api/RStreamAsync.java, redisson/src/main/java/org/redisson/api/RStreamReactive.java, redisson/src/main/java/org/redisson/api/RStreamRx.java, redisson/src/main/java/org/redisson/api/stream/StreamCountArgs.java, redisson/src/main/java/org/redisson/api/stream/StreamPendingRangeArgs.java, redisson/src/main/java/org/redisson/api/stream/StreamPendingRangeParams.java, redisson/src/main/java/org/redisson/api/stream/StreamStartIdArgs.java, redisson/src/test/java/org/redisson/RedissonStreamTest.java
[issues/6674](https://github.com/redisson/redisson/issues/6674)
=> improvement - Improve RStream.listPending() method #6674

redisson/src/main/java/org/redisson/RedissonStream.java, redisson/src/main/java/org/redisson/api/stream/StreamAddParams.java, redisson/src/main/java/org/redisson/api/stream/StreamTrimParams.java, redisson/src/main/java/org/redisson/api/stream/StreamTrimStrategyArgs.java, redisson/src/test/java/org/redisson/RedissonStreamTest.java
[issues/6724](https://github.com/redisson/redisson/issues/6724)
=> Feature - Add support of KEEPREF, DELREF and ACKED options to XADD command #6724

redisson/src/main/java/org/redisson/RedissonStream.java, redisson/src/main/java/org/redisson/api/RStream.java, redisson/src/main/java/org/redisson/api/RStreamAsync.java, redisson/src/main/java/org/redisson/api/RStreamReactive.java, redisson/src/main/java/org/redisson/api/RStreamRx.java, redisson/src/main/java/org/redisson/api/stream/BaseReferencesParams.java, redisson/src/main/java/org/redisson/api/stream/StreamAddParams.java, redisson/src/main/java/org/redisson/api/stream/StreamReferencesArgs.java, redisson/src/main/java/org/redisson/api/stream/StreamRemoveArgs.java, redisson/src/main/java/org/redisson/api/stream/StreamRemoveParams.java, redisson/src/main/java/org/redisson/api/stream/StreamTrimParams.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonStreamTest.java
[issues/6721](https://github.com/redisson/redisson/issues/6721)
=> Feature - Add XDELEX command support #6721

redisson/src/main/java/org/redisson/MapCacheNativeWrapper.java, redisson/src/main/java/org/redisson/RedissonMapCache.java, redisson/src/main/java/org/redisson/api/RMapCache.java, redisson/src/main/java/org/redisson/api/RMapCacheAsync.java, redisson/src/main/java/org/redisson/api/RMapCacheReactive.java, redisson/src/main/java/org/redisson/api/RMapCacheRx.java, redisson/src/test/java/org/redisson/RedissonMapCacheTest.java
[issues/6739](https://github.com/redisson/redisson/issues/6739)
=> Feature - Adding a compute method with ttl for RMapCache #6739

redisson/src/main/java/org/redisson/RedissonScoredSortedSet.java, redisson/src/main/java/org/redisson/RedissonSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSet.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetAsync.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetReactive.java, redisson/src/main/java/org/redisson/api/RScoredSortedSetRx.java, redisson/src/main/java/org/redisson/api/RSortedSet.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/test/java/org/redisson/RedissonSortedSetTest.java
[issues/3533](https://github.com/redisson/redisson/issues/3533)
=> Feature - pollFirst & pollLast in RSortedSet are missing #3533

redisson/src/main/java/org/redisson/RedissonVectorSet.java, redisson/src/main/java/org/redisson/api/RVectorSet.java, redisson/src/main/java/org/redisson/api/RVectorSetAsync.java, redisson/src/main/java/org/redisson/api/RVectorSetReactive.java, redisson/src/main/java/org/redisson/api/RVectorSetRx.java, redisson/src/main/java/org/redisson/api/vector/VectorSimilarArgs.java, redisson/src/main/java/org/redisson/api/vector/VectorSimilarParams.java, redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java, redisson/src/main/java/org/redisson/client/protocol/ScoreAttributesEntry.java, redisson/src/main/java/org/redisson/client/protocol/decoder/ScoredAttributesReplayDecoder.java, redisson/src/main/java/org/redisson/client/protocol/decoder/ScoredAttributesReplayDecoderV2.java, redisson/src/main/java/org/redisson/connection/ServiceManager.java, redisson/src/test/java/org/redisson/RedissonVectorSetTest.java
[issues/6763](https://github.com/redisson/redisson/issues/6763)
=> Feature - Add WITHATTRIBS and EPSILON parameters for VSIM command in RVectorSet object #6763

redisson/src/main/java/org/redisson/RedissonSearch.java, redisson/src/main/java/org/redisson/api/search/index/FieldIndex.java, redisson/src/main/java/org/redisson/api/search/index/GeoShapeIndex.java, redisson/src/main/java/org/redisson/api/search/index/GeoShapeIndexParams.java, redisson/src/test/java/org/redisson/RedissonSearchTest.java
[issues/6785](https://github.com/redisson/redisson/issues/6785)
=> Feature - Add GEOSHAPE field type in RSearch#createIndex() method #6785
